const root=document.getElementById('design');let showRequest=0;
async function show(name){const request=++showRequest,allowed=['home','new-project','feedback','plan','candidates','preview'];if(!allowed.includes(name))name='home';const html=await(await fetch('screens/'+name+'.html')).text();if(request!==showRequest)return;root.innerHTML=html;if(!await geometry(name,()=>request===showRequest))return;applyExampleContent(name);root.dataset.screen=name;wire(name);mountExampleVideos(name);document.title='TikTok Shop Video Studio';scale();}
function setSize(el,width,height){if(!el)return;if(width!=null)el.style.width=typeof width==='number'?width+'px':width;if(height!=null)el.style.height=typeof height==='number'?height+'px':height;}
function fitVideoTimeline(video,ratio){
 const section=video?.querySelector('[data-name^="Shot Timeline Track Section"]');if(!section)return;const baseWidth=parseFloat(section.style.width)||section.getBoundingClientRect().width/ratio,inverse=1/ratio;let row=section.querySelector('.stable-timeline-row');
 if(!row){const icons=[...section.querySelectorAll('img')].map(img=>img.cloneNode(true));row=document.createElement('div');row.className='stable-timeline-row';row.innerHTML='<div class="timeline-start"><button type="button" class="timeline-play" aria-label="Play or pause video"></button><p class="timeline-current">00:00</p><span>/</span><p class="timeline-duration">00:47</p></div><div class="stable-timeline-track" aria-label="Video progress"><div class="timeline-segment"></div><div class="timeline-segment"></div><div class="timeline-segment"></div><div class="timeline-segment"></div><i class="timeline-thumb"></i></div><div class="timeline-end"><button type="button" class="timeline-volume" aria-label="Mute or unmute"></button><button type="button" class="timeline-fullscreen" aria-label="Enter fullscreen"></button></div>';const [play,volume,fullscreen]=row.querySelectorAll('button');[[play,icons[0]],[volume,icons[1]],[fullscreen,icons[2]]].forEach(([button,img])=>{if(img)button.append(img);});play.onclick=e=>{e.stopPropagation();togglePlayback(video.querySelector('.demo-video'));};volume.onclick=e=>{e.stopPropagation();const media=video.querySelector('.demo-video');if(media)media.muted=!media.muted;};fullscreen.onclick=e=>{e.stopPropagation();video.querySelector('.demo-video-stage')?.requestFullscreen?.();};const track=row.querySelector('.stable-timeline-track');track.onclick=e=>{const media=video.querySelector('.demo-video'),rect=track.getBoundingClientRect();if(media?.duration)media.currentTime=Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width))*media.duration;};section.replaceChildren(row);}
 Object.assign(row.style,{width:(baseWidth*ratio)+'px',transform:`scale(${inverse})`,transformOrigin:'left top'});updateTimeline(clock,video.querySelector('.demo-video')?.duration||46.8);
}
function fitWorkspace(main,video,panel,baseWidth,baseHeight,topInset=16,bottomInset=16){
 if(!main||!video||!panel)return;
 const mainWidth=main.getBoundingClientRect().width||parseFloat(main.style.width)||1220;
 const mainHeight=main.getBoundingClientRect().height||parseFloat(main.style.height)||784;
 const availableHeight=Math.max(480,mainHeight-topInset-bottomInset);
 const maxVideoWidth=Math.max(360,mainWidth-32-420-16);
 const ratio=Math.min(availableHeight/baseHeight,maxVideoWidth/baseWidth);
 const visualWidth=Math.round(baseWidth*ratio);
 const visualHeight=Math.round(baseHeight*ratio);
 const panelHeight=availableHeight;
 const fittedBaseHeight=panelHeight/ratio;Object.assign(video.style,{width:baseWidth+'px',height:fittedBaseHeight+'px',left:'16px',top:topInset+'px',transform:`scale(${ratio})`,transformOrigin:'top left',overflow:'hidden'});
 const fixedTextHeaders={'11:65375':['11:65377','11:65378'],'11:68666':['11:68668','11:68669'],'14:72848':['14:72896','14:73237']},fixedHeader=fixedTextHeaders[video.dataset.nodeId];if(fixedHeader){const title=node(fixedHeader[0]),action=node(fixedHeader[1]),inverse=1/ratio;if(title)Object.assign(title.style,{transform:`scale(${inverse})`,transformOrigin:'left top',width:'max-content'});if(action)Object.assign(action.style,{left:'auto',right:'0px',transform:`scale(${inverse})`,transformOrigin:'right top'});}
 if(fittedBaseHeight>baseHeight+1){const stage=[...video.querySelectorAll('[data-name^="Main Video Stage"]')].find(el=>!el.dataset.name.includes('Timeline')),stageShell=stage?.parentElement,body=stageShell?.closest('[data-node-id]');if(stage&&body){const bodyHeight=fittedBaseHeight-81,stageHeight=bodyHeight-32;body.style.setProperty('height',bodyHeight+'px','important');Object.assign(stage.style,{position:'absolute',left:'0px',top:'0px',height:stageHeight+'px',minHeight:'0',overflow:'hidden'});const portrait=stage.querySelector(':scope > [data-node-id]');if(portrait)Object.assign(portrait.style,{height:'100%',width:'auto',left:'50%',transform:'translateX(-50%)'});const play=[...stage.querySelectorAll('[data-name^="Central Floating Play"]')].find(el=>!el.dataset.name.endsWith(':shadow'));if(play)Object.assign(play.style,{left:'50%',top:'50%'});const timeline=body.querySelector('[data-name^="Shot Timeline Track"]');if(timeline)Object.assign(timeline.style,{position:'absolute',left:'0px',top:(stageHeight+16)+'px'});}}
 fitVideoTimeline(video,ratio);
 Object.assign(panel.style,{left:(32+visualWidth)+'px',top:topInset+'px',width:Math.max(360,mainWidth-48-visualWidth)+'px',height:panelHeight+'px',transform:'none'});
 const panelBackground=panel.firstElementChild;if(panelBackground&&(panelBackground.classList.contains('absolute')||parseFloat(panelBackground.style.height||0)>baseHeight*.75))Object.assign(panelBackground.style,{inset:'0px',width:'100%',height:'100%'});
 panel.querySelectorAll(':scope > [data-node-id], :scope > .cards-scroll').forEach(el=>{if(el.classList.contains('cards-scroll'))return;const left=parseFloat(el.style.left||0),elementHeight=parseFloat(el.style.height||0);if(left<=20)el.style.width=left===0?'100%':'calc(100% - 32px)';if(left<=0&&elementHeight>=56&&elementHeight<=70){el.style.left='-1px';el.style.top='auto';el.style.bottom='-1px';el.style.width='calc(100% + 2px)';}});
 const sc=panel.querySelector('.cards-scroll');if(sc){const scTop=parseFloat(sc.style.top)||110;sc.style.width='100%';sc.style.height=Math.max(120,panelHeight-scTop-62)+'px';sc.querySelectorAll(':scope > [data-node-id]').forEach(el=>el.style.width=sc.classList.contains('flow-scroll')?'100%':'calc(100% - 32px)');}
}
function fitFeedbackContent(panel){
 if(!panel)return;
 const header=node('25:82600'),headerInner=node('25:82601'),steps=node('25:82617'),intro=node('25:82623'),introText=node('25:82630'),compact=panel.getBoundingClientRect().width<520;if(header)Object.assign(header.style,{width:'calc(100% - 32px)',height:(compact?110:74)+'px'});if(headerInner)headerInner.style.width='100%';if(steps)Object.assign(steps.style,{left:'auto',right:'0px',top:(compact?36:4)+'px',transform:'none',transformOrigin:'right center'});if(intro)Object.assign(intro.style,{top:(compact?72:36)+'px',width:'100%',height:'20px'});if(introText)Object.assign(introText.style,{width:'100%',height:'20px',lineHeight:'20px',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'});const sc=panel.querySelector('.cards-scroll');if(sc&&intro){const panelRect=panel.getBoundingClientRect(),introRect=intro.getBoundingClientRect(),top=introRect.bottom-panelRect.top-panel.clientTop+16;Object.assign(sc.style,{top:top+'px',height:Math.max(120,panelRect.height-top-62)+'px'});}
 const cards=[{card:'25:82631',header:'25:82632',title:'25:82633',chevron:'25:82636',description:'25:82637',question:'25:82638',prompt:'25:82639',options:'25:82641',add:'25:82645'},{card:'25:82646',header:'25:82647',title:'25:82648',chevron:'25:82656',description:'25:82657',question:'25:82658',prompt:'25:82659',options:'25:82661',add:'25:82665'}];
 cards.forEach((cfg,index)=>{const card=node(cfg.card),head=node(cfg.header),title=node(cfg.title),chevron=node(cfg.chevron),description=node(cfg.description),question=node(cfg.question),prompt=node(cfg.prompt),options=node(cfg.options),add=node(cfg.add);if(!card)return;if(head)head.style.width='calc(100% - 24px)';if(title)title.style.width='calc(100% - 24px)';if(chevron)Object.assign(chevron.style,{left:'auto',right:'0px'});if(description)description.style.width='calc(100% - 24px)';if(question)Object.assign(question.style,{width:'calc(100% - 24px)',height:'auto',display:'flex',flexDirection:'column',gap:'10px',alignItems:'flex-start',paddingTop:'12px'});if(prompt){Object.assign(prompt.style,{position:'relative',left:'auto',top:'auto',width:'100%',height:'auto',display:'block'});prompt.querySelectorAll('p').forEach(p=>Object.assign(p.style,{position:'relative',left:'auto',top:'auto',width:'auto',height:'auto'}));}if(options){Object.assign(options.style,{position:'relative',left:'auto',top:'auto',width:'100%',height:'auto',display:'flex',flexWrap:'wrap',gap:'8px'});[...options.children].forEach(option=>{Object.assign(option.style,{position:'relative',left:'auto',top:'auto',width:'auto',height:'auto'});option.querySelectorAll('p').forEach(p=>Object.assign(p.style,{position:'relative',left:'auto',top:'auto',width:'auto',height:'auto'}));});}if(add)Object.assign(add.style,{position:'relative',left:'auto',top:'auto'});if(state.shotOpen[index]&&question){const needed=113+question.scrollHeight+16;card.style.height=Math.max(index?261:223,needed)+'px';}});
 const footer=node('25:82688'),footerInfo=node('25:82689'),footerButton=node('25:82692'),panelWidth=panel.getBoundingClientRect().width;if(footer)footer.style.width='calc(100% + 2px)';if(footerInfo){footerInfo.style.left='16px';footerInfo.style.display=panelWidth<420?'none':'flex';}if(footerButton)Object.assign(footerButton.style,{left:'auto',right:'16px'});
}
function fitPreviewContent(panel){
 if(!panel)return;const header=node('14:73265'),title=node('14:73393'),summary=node('14:73395'),scroll=panel.querySelector('.cards-scroll'),footer=node('14:73351');
 if(header){Object.assign(header.style,{left:'16px',top:'20px',width:'calc(100% - 32px)',height:'auto',display:'flex',flexDirection:'column',alignItems:'flex-start',gap:'8px'});[...header.children].forEach(child=>Object.assign(child.style,{position:'relative',left:'auto',top:'auto',transform:'none'}));}
 if(title)Object.assign(title.style,{width:'auto',height:'23px',lineHeight:'23px',display:'block'});
 if(summary)Object.assign(summary.style,{width:'100%',height:'auto'});
 if(scroll&&header){const panelRect=panel.getBoundingClientRect(),headerRect=header.getBoundingClientRect(),top=headerRect.bottom-panelRect.top-panel.clientTop+16;Object.assign(scroll.style,{left:'0px',top:top+'px',width:'100%',height:Math.max(120,panelRect.height-top-62)+'px',overflowY:'auto'});}
 const cards=['14:73296','14:73311','14:73331','14:73406','16:73462'].map(node).filter(Boolean);cards.forEach((card,index)=>{Object.assign(card.style,{left:'16px',width:'calc(100% - 32px)'});[...card.children].slice(1).forEach(child=>child.style.width='calc(100% - 24px)');const head=card.firstElementChild;if(head)Object.assign(head.style,{width:'calc(100% - 24px)',display:'flex',alignItems:'center'});const titleRow=head?.firstElementChild;if(titleRow){Object.assign(titleRow.style,{width:'calc(100% - 24px)',display:'flex',alignItems:'center',gap:'8px'});[...titleRow.children].forEach((child,childIndex)=>Object.assign(child.style,{position:'relative',left:'auto',top:'auto',width:index>0&&childIndex===0?'16px':'auto',height:index>0&&childIndex===0?'18px':child.style.height,flex:index>0&&childIndex===0?'none':child.style.flex}));}card.querySelectorAll('p.min-w-px').forEach(p=>Object.assign(p.style,{left:'8px',top:'4px',width:'calc(100% - 16px)',height:'auto',whiteSpace:'normal',overflow:'hidden'}));const chevron=head?.lastElementChild;if(chevron)Object.assign(chevron.style,{position:'absolute',left:'auto',right:'0px',top:'4px'});});
 ['14:73302','14:73322','14:73342','14:73417','16:73473'].map(node).filter(Boolean).forEach(p=>Object.assign(p.style,{width:'calc(100% - 24px)',height:'auto',whiteSpace:'normal'}));
 if(footer){Object.assign(footer.style,{left:'-1px',bottom:'-1px',width:'calc(100% + 2px)',display:'flex',justifyContent:'flex-end',alignItems:'center',gap:'12px',paddingLeft:'16px',paddingRight:'20px'});[...footer.children].forEach(button=>Object.assign(button.style,{position:'relative',left:'auto',top:'auto'}));}
}
function fitPlanContent(panel){
 if(!panel)return;
 const available='calc(100% - 22px)';
 const header=node('11:68725'),steps=node('11:68865');if(header)header.style.width='100%';if(steps)Object.assign(steps.style,{left:'auto',right:'0px',transform:'scale(.74)',transformOrigin:'right center'});
 const questions=node('11:68755'),groups=[node('11:68762'),node('13:69042')],containers=[node('11:68765'),node('13:69046')];
 if(questions)questions.style.width='100%';
 groups.forEach(group=>{if(group)group.style.width=available;});
 containers.forEach(container=>{if(container)container.style.width='100%';});
 ['13:69039','13:69044'].map(node).filter(Boolean).forEach(title=>Object.assign(title.style,{position:'relative',left:'auto',top:'auto',width:'auto',height:'auto'}));
 [[node('13:69038'),node('13:69266')],[node('13:69043'),node('13:69256')]].forEach(([row,tags])=>{if(row){Object.assign(row.style,{width:'100%',display:'flex',alignItems:'center',gap:'8px'});[...row.children].forEach(child=>Object.assign(child.style,{position:'relative',left:'auto',top:'auto'}));}if(tags)Object.assign(tags.style,{position:'relative',left:'auto',top:'auto',flex:'none'});});
 panel.querySelectorAll('[data-name="Tag Radio"]').forEach(option=>{option.style.width='100%';[...option.children].forEach((child,index)=>Object.assign(child.style,{position:'relative',left:'auto',top:'auto',width:index?'calc(100% - 25px)':'auto',height:'auto'}));option.querySelectorAll('p').forEach(p=>Object.assign(p.style,{position:'relative',left:'auto',top:'auto',maxWidth:'100%',height:'auto',whiteSpace:'nowrap'}));});
 [node('11:68756'),node('11:68757')].forEach(el=>{if(el)el.style.width='100%';});
 const planned=node('13:69198');if(planned)planned.style.width='100%';
 const plannedOuterHead=node('13:69199'),plannedHead=node('13:69200'),plannedTitle=node('13:69201'),plannedChevron=node('13:69253'),changes=node('13:69287');if(plannedOuterHead)plannedOuterHead.style.width='calc(100% - 22px)';if(plannedHead)plannedHead.style.width='100%';if(plannedTitle)plannedTitle.style.width='auto';if(plannedChevron)Object.assign(plannedChevron.style,{left:'auto',right:'0px'});if(changes)changes.style.width='calc(100% - 22px)';[node('13:69272'),node('13:69281')].filter(Boolean).forEach(row=>row.style.width='100%');[[node('13:69273'),node('13:69278')],[node('13:69282'),node('13:69284')]].forEach(([content,tag])=>{if(content)content.style.width='calc(100% - 50px)';if(tag)Object.assign(tag.style,{left:'auto',right:'7px'});});[node('13:69274'),node('13:69283')].filter(Boolean).forEach(text=>Object.assign(text.style,{width:'100%',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}));
 const footer=node('11:68810'),actions=node('13:69323'),status=node('11:68811');
 if(footer)footer.style.width='calc(100% + 2px)';
 if(actions)Object.assign(actions.style,{left:'auto',right:'16px'});
 if(status)status.style.display=panel.getBoundingClientRect().width<520?'none':'flex';
}
function adaptLayout(name){
 const width=Math.max(innerWidth,768),height=innerHeight,collapsed=!!state.sidebarCollapsed,sidebarWidth=collapsed?56:220;
 const screen=root.firstElementChild;setSize(root,width,height);setSize(screen,width,height);root.style.transform='none';
 const viewport=document.getElementById('viewport');viewport.style.height='100vh';viewport.style.width='100vw';
 const configs={
  home:{content:'17:75425',sidebar:'17:75358',main:'17:75178',offset:52},
  'new-project':{content:'25:81938',sidebar:'25:81939',main:'25:81991',offset:52},
  feedback:{content:'11:65311',sidebar:'16:73477',main:'11:65374',offset:116,video:'11:65375',panel:'25:82580',vw:631,vh:752},
  plan:{content:'11:68602',sidebar:'25:81381',main:'11:68665',offset:116,video:'11:68666',panel:'11:68704',vw:631,vh:752}
 };
 const c=configs[name];
 if(c){
  const content=node(c.content),sidebar=node(c.sidebar),main=node(c.main);setSize(content,width,height-c.offset);setSize(sidebar,sidebarWidth,height-c.offset);setSize(main,width-sidebarWidth,height-c.offset);if(main)main.style.left=sidebarWidth+'px';
  sidebar?.classList.toggle('sidebar-collapsed',collapsed);main&&(main.style.flex='1 1 auto');
  if(name==='feedback'||name==='plan'){const header=node(name==='feedback'?'16:73478':'25:81382'),newVersion=node(name==='feedback'?'16:73479':'25:81383'),toggle=node(name==='feedback'?'16:73480':'25:81384');if(header)setSize(header,collapsed?32:196,32);if(newVersion)newVersion.style.display=collapsed?'none':'flex';if(toggle){toggle.style.left=collapsed?'0px':'164px';toggle.style.position='absolute';}}
  if(c.video){const panel=node(c.panel);fitWorkspace(main,node(c.video),panel,c.vw,c.vh);if(name==='feedback')fitFeedbackContent(panel);if(name==='plan')fitPlanContent(panel);}
 }
 if(name==='home'){
  const page=node('17:74146'),mainWidth=width-sidebarWidth,hero=node('17:74944'),heroWidth=Math.min(868,Math.max(500,mainWidth-48));setSize(page,mainWidth,height-52);setSize(node('18:81375'),mainWidth,height-50);
  if(hero){setSize(hero,heroWidth,Math.max(566,height-172));hero.style.left='50%';hero.style.transform='translateX(-50%)';const intro=node('17:76212');if(intro)intro.style.left=Math.max(0,(heroWidth-633)/2)+'px';const projects=node('17:74955'),header=node('17:76172'),search=node('17:76177');setSize(projects,heroWidth,null);setSize(header,heroWidth,32);if(search)search.style.left=Math.max(148,heroWidth-287.286)+'px';const cards=['17:76477','17:76495','17:76579','17:76669','17:76651'].map(node).filter(Boolean),columns=heroWidth>=840?3:heroWidth>=560?2:1,gap=12,cardWidth=(heroWidth-gap*(columns-1))/columns;cards.forEach((card,index)=>{projects.append(card);Object.assign(card.style,{left:(index%columns)*(cardWidth+gap)+'px',top:(52+Math.floor(index/columns)*122)+'px',width:cardWidth+'px',height:'110px'});card.querySelectorAll(':scope > [data-node-id]').forEach(el=>el.style.width=parseFloat(el.style.height||0)>30?'calc(100% - 40px)':'16px');});}
 }
 if(name==='new-project'){const page=node('25:81992');setSize(page,width-sidebarWidth,height-52);}
 if(name==='candidates'){
  const candidateSidebarWidth=state.candidateSidebarCollapsed?56:220,content=node('14:72081'),candidateSidebar=node('14:73212');setSize(content,width,height-116);setSize(candidateSidebar,candidateSidebarWidth,height-116);setSize(node('14:72144'),width-candidateSidebarWidth,height-116);
  const main=node('14:72144');if(main)Object.assign(main.style,{left:candidateSidebarWidth+'px',overflow:'hidden'});
  const agentHeight=state.generating?140:95,rowTop=state.generating?172:127,footerTop=height-168,rowHeight=Math.max(280,footerTop-rowTop-16),workspaceWidth=width-candidateSidebarWidth-32;setSize(node('14:72183'),workspaceWidth,agentHeight);setSize(node('14:72234'),workspaceWidth,rowHeight);setSize(node('14:72384'),workspaceWidth,36);const row=node('14:72234');if(row)Object.assign(row.style,{top:rowTop+'px',overflow:'hidden'});const footer=node('14:72384');if(footer)Object.assign(footer.style,{top:footerTop+'px',overflow:'visible'});
  const agent=node('14:72183'),agentBg=node('14:72184'),agentContent=node('14:72203'),agentHeader=node('14:72204'),steps=node('14:72220'),agentCopy=node('14:72226');if(agent)agent.style.overflow='hidden';if(agentBg)Object.assign(agentBg.style,{inset:'0px',width:'100%',height:'100%',backgroundSize:'100% 100%'});if(agentContent)Object.assign(agentContent.style,{left:'16px',width:'calc(100% - 32px)'});if(agentHeader)agentHeader.style.width='100%';if(steps)Object.assign(steps.style,{left:'auto',right:'0px'});if(agentCopy){Object.assign(agentCopy.style,{width:'100%',height:'34px'});const copy=agentCopy.querySelector('p');if(copy)Object.assign(copy.style,{position:'relative',left:'0px',top:'0px',width:'100%',height:'auto',display:'-webkit-box',WebkitBoxOrient:'vertical',WebkitLineClamp:'2',whiteSpace:'normal',overflow:'hidden'});}
  const cardIds=['14:72235','14:72276','14:72317'],rowWidth=workspaceWidth,cardWidth=(rowWidth-32)/3;
  const headIds=['14:72236','14:72277','14:72318'],titleIds=['14:72237','14:72278','14:72319'],descriptionIds=['14:72239','14:72279','14:72320'],stageIds=['14:72240','14:72280','14:72321'],portraitIds=['14:72241','14:72281','14:72322'],playIds=['14:72242','14:72283','14:72323'],timelineIds=['14:72246','14:72287','14:72327'];
  cardIds.forEach((id,index)=>{const card=node(id);if(!card)return;Object.assign(card.style,{left:(index*(cardWidth+16))+'px',width:cardWidth+'px',height:rowHeight+'px',flex:'none',overflow:'hidden'});const head=node(headIds[index]),title=node(titleIds[index]),description=node(descriptionIds[index]),stage=node(stageIds[index]),portrait=node(portraitIds[index]),play=node(playIds[index]),timeline=node(timelineIds[index]);if(head)Object.assign(head.style,{left:'12px',width:'calc(100% - 24px)'});if(title)title.style.width='calc(100% - 74px)';if(description)Object.assign(description.style,{width:'100%',minWidth:'0'});if(stage)Object.assign(stage.style,{left:'12px',top:'84px',width:'calc(100% - 24px)',height:Math.max(170,rowHeight-96)+'px',minHeight:'0',overflow:'hidden'});if(portrait)Object.assign(portrait.style,{height:'100%',width:'auto',left:'50%',transform:'translateX(-50%)'});if(play)play.style.left='50%';if(timeline)Object.assign(timeline.style,{left:'50%',width:Math.max(180,Math.min(335,cardWidth-40))+'px'});});
  const footerActions=node('14:72387'),footerMessage=node('14:72385');if(footerActions)Object.assign(footerActions.style,{left:'auto',right:'0px'});['14:72388','14:72398','14:72389'].map(node).filter(Boolean).forEach(button=>{Object.assign(button.style,{display:'flex',alignItems:'center',justifyContent:'center',gap:'8px'});[...button.children].forEach(child=>Object.assign(child.style,{position:'relative',left:'auto',top:'auto'}));});if(footerMessage)footerMessage.style.display=rowWidth<930?'none':'flex';
 }
 if(name==='preview'){
  const content=node('14:72489'),outer=node('14:73201'),workspace=node('14:73244');setSize(content,width,height-52);setSize(outer,width-32,height-84);setSize(workspace,width-32,height-122);
  if(workspace){workspace.style.width='100%';const previewPanel=node('14:73245');fitWorkspace(workspace,node('14:72848'),previewPanel,851,778,0,16);fitPreviewContent(previewPanel);}
 }
 root.querySelectorAll('[data-node-id$="68931"],[data-node-id="16:73796"],[data-node-id="14:71994"],[data-node-id="14:72402"],[data-node-id="25:81883"],[data-node-id="11:68872"]').forEach(el=>el.style.width='100%');
 root.querySelectorAll('[data-node-id="11:67504"],[data-node-id="25:81450"],[data-node-id="25:81487"]').forEach(el=>el.style.width='100%');
}
function scale(){adaptLayout(root.dataset.screen||'home');}

async function geometry(name,isCurrent=()=>true){
 const ids={home:'16-73795','new-project':'25-81862',feedback:'11-65277',plan:'11-68513',candidates:'14-71993',preview:'14-72401'};
 const list=await(await fetch('source/geo-'+ids[name]+'.json')).json();
 const map=new Map(list.map(r=>[r[0],r]));const rotations=new Map(await(await fetch('source/rotations.json')).json());if(!isCurrent())return false;
 for(const [id,parent,x,y,w,h,fonts] of list){
  const el=root.querySelector('[data-node-id="'+id+'"]');if(!el)continue;
  el.style.width=w+'px';el.style.height=h+'px';el.style.flex='none';el.style.minWidth='0';el.style.minHeight='0';
  const siblings=[...el.parentElement.children];const positioned=siblings.every(s=>map.get(s.dataset.nodeId)?.[1]===parent&&!/translate|rotate|skew/.test(s.className)&&!s.style.transform);
  if(el.parentElement.dataset.nodeId===parent&&positioned){const ps=getComputedStyle(el.parentElement);Object.assign(el.style,{position:'absolute',left:(x-(Math.abs(rotations.get(id)||0)>179?w:0)-parseFloat(ps.borderLeftWidth||0))+'px',top:(y-(Math.abs(rotations.get(id)||0)>179?h:0)-parseFloat(ps.borderTopWidth||0))+'px',right:'auto',bottom:'auto',margin:0});}
  if(fonts?.length===1){const f=fonts[0];el.style.fontFamily='"'+f.family+'"';el.style.fontWeight=/Semi Bold/.test(f.style)?600:/Bold/.test(f.style)?700:/Medium/.test(f.style)?500:400;}
 }return true;
}

const DEMO_VIDEO='assets/video/example-product-video.mp4';
const candidateNames=['Clear Benefit Edit','Travel Proof','Personal Review'];
const candidateDescriptions=['A structured edit that separates texture, protection, personal proof, and supporting claims so each benefit is easier to understand.','A proof-led version that opens with the high-UV Lijiang trip, then connects the result to protection, texture, and daily use.','A conversational review that keeps the creator’s personal tone, trims dense claim stacking, and ends with a calmer recommendation.'];
const plannedDefaults=['Separate the texture and protection benefits in the opening so each claim is easier to follow.','Slow down the Lijiang proof point and connect it directly to the no-sunburn and no-tanning result.'];
const feedbackSections=[
 {title:'Whole Video',options:['Feels information-heavy','Pacing feels rushed','Claims need clearer proof']},
 {title:'Shot 1: Fresh Feel + SPF50+',options:['Too many benefits arrive at once','The SPF rating is hard to catch','The hook feels too absolute']},
 {title:'Shot 2: Lijiang Proof',options:['The travel story feels compressed','The result needs more context']},
 {title:'Shot 3: Soothing Benefits',options:['The ingredient claims move too quickly','The sensitive-skin benefit needs emphasis']},
 {title:'Shot 4: Reef-Friendly Close',options:['The environmental claim feels abrupt','The ending packs in too many claims']}
];
const stateKey='tiktok-figma-exact-state';let state;try{state=JSON.parse(localStorage.getItem(stateKey))}catch{}state={selected:null,previewCandidate:0,feedback:[],customFeelings:[[],[],[],[],[]],choices:[null,null],customDirections:[[],[]],skipped:[false,false],shotOpen:[true,true,false,false,false],previewShotOpen:[true,false,false,false,false],versionOpen:[true,false,false],versions:[{base:'Source Video',generated:false}],currentVersion:0,rounds:[],plannedChanges:[...plannedDefaults],projectName:'Lightweight Sunscreen Review',base:'Source Video',sidebarCollapsed:false,candidateSidebarCollapsed:true,generating:false,generationStartedAt:0,...(state||{})};if(state.schemaVersion!==5){state.selected=null;state.previewCandidate=0;state.feedback=[];state.customFeelings=[[],[],[],[],[]];state.choices=[null,null];state.customDirections=[[],[]];state.skipped=[false,false];state.shotOpen=[true,true,false,false,false];state.previewShotOpen=[true,false,false,false,false];state.versionOpen=[true,false,false];state.versions=[{base:'Source Video',generated:false}];state.currentVersion=0;state.plannedChanges=[...plannedDefaults];state.projectName='Lightweight Sunscreen Review';state.base='Source Video';state.generating=false;state.schemaVersion=5;}if(state.shotOpen.length<5)state.shotOpen=[true,true,false,false,false];if(!Array.isArray(state.previewShotOpen)||state.previewShotOpen.length<5)state.previewShotOpen=[true,false,false,false,false];if(!Array.isArray(state.customFeelings)||state.customFeelings.length<5)state.customFeelings=[[],[],[],[],[]];let selectedFile=null,sourceUrl=null,playing=null,generationTimer=null,transitionTimer=null,clock=0;
let migratedVersionNames=false;state.versions.forEach(version=>{const match=/^Candidate \d+-([A-C])$/.exec(version.base||'');if(match){version.base=candidateNames[match[1].charCodeAt(0)-65];migratedVersionNames=true;}});{const match=/^Candidate \d+-([A-C])$/.exec(state.base||'');if(match){state.base=candidateNames[match[1].charCodeAt(0)-65];migratedVersionNames=true;}}
const persist=()=>localStorage.setItem(stateKey,JSON.stringify(state));if(migratedVersionNames)persist();
const node=id=>root.querySelector('[data-node-id="'+id+'"]');
function replaceText(from,to){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let current;while(current=walker.nextNode())if(current.nodeValue.includes(from))current.nodeValue=current.nodeValue.split(from).join(to);}
function applyExampleContent(name){
 const replacements=[
  ['Summer Sunscreen Cushion','Lightweight Sunscreen Review'],['Sunscreen_cushion.mp4','sunscreen-review.mp4'],['01:24','00:47'],['00:06','00:00'],
  ['A Tighter Edit','Clear Benefit Edit'],['Product in Use','Travel Proof'],['An Everyday Story','Personal Review'],
  ['Shot 1: Straight to the Routine','Shot 1: Fresh Feel + SPF50+'],['Shot 2: Meet the Cushion','Shot 2: Lijiang Proof'],['Shot 3: Apply and Blend','Shot 3: Soothing Benefits'],['Shot 4: The Finished Look','Shot 4: Reef-Friendly Close'],
  ['(00:00–00:14)','(00:00–00:12)'],['(00:14–00:36)','(00:12–00:25)'],['(00:36–00:58)','(00:25–00:34)'],['(00:58–01:12)','(00:34–00:47)'],
  ['Feels too much like an ad','Feels information-heavy'],['Pacing feels slow','Pacing feels rushed'],['Unnatural tone','Claims need clearer proof'],
  ['The opening doesn’t grab me','Too many benefits arrive at once'],['Takes too long to get to the point','The SPF rating is hard to catch'],['The delivery feels scripted','The hook feels too absolute'],
  ['Q1: More Natural Product Placement','Q1: Clarify the Benefit Order'],['Show the compact being picked up and opened','Lead with the lightweight feel'],['Introduce the product through a natural action.','Then introduce the SPF 50+ and PA++++ protection level.'],['Shorten the standalone product close-up','Open with the protection rating'],['Spend less time showing the compact on its own.','Follow it with the lightweight texture benefit.'],
  ['Q2: More Natural Hand Movements','Q2: Strengthen the Personal Proof'],['Make the tapping motion more relaxed','Give the Lijiang proof more space'],['Use smaller, less repetitive movements.','Connect the travel context directly to the result.'],['Smooth out the movement around the nose','Shorten the story and state the result'],['Make the transition from cheek to nose feel continuous.','Keep the pace brisk and make the result explicit.'],
  ['Trim the pause before the first line so the creator starts speaking sooner.',plannedDefaults[0]],['Replace “Shop the cushion now” with “I’ve linked the cushion if you’re curio-us.” Keep the shot of the compact going into the bag.',plannedDefaults[1]]
 ];replacements.forEach(([from,to])=>replaceText(from,to));
 const exact={
  '25:82637':'A creator recommends a high-protection sunscreen, highlights its lightweight and hydrating feel, supports the claim with a Lijiang travel experience, then closes with soothing, sensitive-skin and reef-friendly benefits.',
  '25:82657':'The creator opens with a strong recommendation, contrasts SPF50+ PA++++ protection with a fresh, non-greasy feel, and quickly stacks the core product benefits.',
  '14:72233':'We’ve created three candidates from your feedback: one clarifies the benefit hierarchy, one leads with the Lijiang proof, and one keeps the review softer and more personal.',
  '14:72239':'A structured edit that separates texture, protection, personal proof, and supporting claims so each benefit is easier to understand.',
  '14:72279':'A proof-led version that opens with the high-UV Lijiang trip, then connects the result to protection, texture, and daily use.',
  '14:72320':'A conversational review that keeps the creator’s personal tone, trims dense claim stacking, and ends with a calmer recommendation.',
  '14:73302':'The creator recommends a lightweight SPF50+ PA++++ sunscreen, supports it with a high-UV travel experience, and adds soothing, sensitive-skin and reef-friendly benefits.',
  '14:73322':'The opening separates the fresh texture from the protection rating so both benefits are easier to understand.',
  '14:73342':'The Lijiang trip becomes the central proof point, linking strong UV exposure directly to the no-sunburn and no-tanning result.',
  '14:73417':'Centella, soothing care, and the low-irritation formula are grouped into one concise sensitive-skin benefit.',
  '16:73473':'The reef-friendly point and social proof form a shorter close with a calmer final recommendation.'
 };Object.entries(exact).forEach(([id,text])=>{const el=node(id);if(el)el.textContent=text;});
 const firstProjectCount=node('17:76569')?.querySelector('p');if(firstProjectCount)firstProjectCount.textContent='1 version';
 if(name!=='home'){const projectTitle=[...root.querySelectorAll('p')].find(p=>p.textContent.trim()==='Lightweight Sunscreen Review');if(projectTitle){const titleRow=projectTitle.parentElement;Object.assign(titleRow.style,{width:'auto',height:'auto',display:'flex',alignItems:'center'});[...titleRow.children].forEach(child=>Object.assign(child.style,{position:'relative',left:'auto',top:'auto'}));Object.assign(projectTitle.style,{width:'max-content',height:'auto'});}}
 const shotTags={'13:69268':'Shot1','13:69270':'Shot3','13:69257':'Shot2'};Object.entries(shotTags).forEach(([id,text])=>{const p=node(id)?.querySelector('p');if(p)p.textContent=text;});
}
function updateTimeline(seconds,duration=46.8){const active=seconds<12?0:seconds<25?1:seconds<34?2:3;root.querySelectorAll('[data-name^="Shot Timeline Track Section"]').forEach(section=>{const stable=[...section.querySelectorAll('.timeline-segment')];if(stable.length){stable.forEach((bar,index)=>bar.classList.toggle('active',index===active));const thumb=section.querySelector('.timeline-thumb'),current=section.querySelector('.timeline-current'),total=section.querySelector('.timeline-duration');if(thumb)thumb.style.left=Math.max(0,Math.min(100,seconds/duration*100))+'%';if(current)current.textContent='00:'+String(Math.floor(seconds)).padStart(2,'0');if(total)total.textContent='00:'+String(Math.ceil(duration)).padStart(2,'0');return;}const bars=[...section.querySelectorAll('div')].filter(el=>{const r=el.getBoundingClientRect(),bg=getComputedStyle(el).backgroundColor;return r.height<=6&&r.width>10&&bg!=='rgba(0, 0, 0, 0)';}).slice(0,4);bars.forEach((bar,index)=>bar.style.backgroundColor=index===active?'#0077fa':'#d9d9d9');const track=bars[0]?.parentElement,thumb=track?.querySelector('[data-name="Background+Border"]');if(thumb)thumb.style.left=Math.max(0,Math.min(100,seconds/duration*100))+'%';});}
function syncCentralPlay(video){const stage=video?.closest('[data-name^="Main Video Stage"]'),control=[...(stage?.querySelectorAll('[data-name^="Central Floating Play"]')||[])].find(el=>!el.dataset.name.endsWith(':shadow')),active=!!video&&!video.paused&&!video.ended;if(stage)stage.classList.toggle('video-is-playing',active);if(control){control.classList.add('central-play-control');control.classList.toggle('video-playing',active);control.setAttribute('aria-label',active?'Pause video':'Play video');}}
function mountExampleVideos(name){
 const stages=name==='candidates'?['14:72240','14:72280','14:72321'].map(node):[...root.querySelectorAll('[data-name^="Main Video Stage"]')];
 stages.filter(Boolean).forEach((stage,index)=>{if(stage.querySelector('.demo-video'))return;stage.classList.add('demo-video-stage');const video=document.createElement('video');video.className='demo-video';video.src=sourceUrl||DEMO_VIDEO;video.poster=sourceUrl?'':'assets/video/example-product-poster.jpg';video.preload='auto';video.playsInline=true;video.setAttribute('aria-label',name==='candidates'?'Candidate '+String.fromCharCode(65+index)+' video preview':'Source video preview');Object.assign(video.style,{position:'absolute',inset:'0',width:'100%',height:'100%',objectFit:'contain',background:'#f5f6f8',zIndex:'1'});stage.prepend(video);const play=[...stage.querySelectorAll('[data-name^="Central Floating Play"]')].find(el=>!el.dataset.name.endsWith(':shadow'));if(play){play.style.zIndex='3';play.classList.add('central-play-control');}video.addEventListener('loadedmetadata',()=>{root.querySelectorAll('p').forEach(p=>{if(p.textContent.trim()==='01:24'||p.textContent.trim()==='00:47')p.textContent='00:47';});updateTimeline(video.currentTime,video.duration);syncCentralPlay(video);});video.addEventListener('play',()=>syncCentralPlay(video));video.addEventListener('pause',()=>syncCentralPlay(video));video.addEventListener('ended',()=>syncCentralPlay(video));video.addEventListener('timeupdate',()=>{clock=Math.floor(video.currentTime);root.querySelectorAll('p').forEach(p=>{if(/^00:\d{2}$/.test(p.textContent.trim())&&p.textContent.trim()!=='00:47')p.textContent='00:'+String(clock).padStart(2,'0');});updateTimeline(video.currentTime,video.duration);});video.onclick=e=>{e.stopPropagation();togglePlayback(video);};syncCentralPlay(video);});updateTimeline(0);
}
function tell(message){const n=document.getElementById('notice');n.textContent=message;n.style.display='block';setTimeout(()=>n.style.display='none',4000);}
function clearTransition(){clearTimeout(transitionTimer);transitionTimer=null;document.querySelector('.page-transition-overlay')?.remove();}
function transitionTo(name){clearTransition();const overlay=document.createElement('div');overlay.className='page-transition-overlay';overlay.setAttribute('role','status');overlay.setAttribute('aria-label','Loading');overlay.innerHTML='<span class="page-transition-spinner" aria-hidden="true"></span>';document.body.append(overlay);transitionTimer=setTimeout(()=>{transitionTimer=null;overlay.remove();nav(name);},3000);}
function nav(name){if(playing?.pause)playing.pause();else clearInterval(playing);playing=null;clearTimeout(generationTimer);generationTimer=null;clearTransition();showRequest++;location.hash=name;if(root.dataset.screen===name)show(name);}
function leaf(text){return [...root.querySelectorAll('p,span,div')].find(el=>el.textContent.trim()===text&&(!el.children.length||el.tagName==='P'));}
function click(el,fn,label){if(!el)return;el.classList.add('interactive');el.tabIndex=0;el.setAttribute('role','button');if(label)el.setAttribute('aria-label',label);el.onclick=e=>{e.stopPropagation();fn(e);};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fn(e);}};}
function button(text,fn){let el=leaf(text);if(!el)return;let outer=el;for(let p=el.parentElement;p&&p!==root;p=p.parentElement){if(/^Button/.test(p.dataset.name||'')){outer=p;break;}}click(outer,fn,text);return outer;}
function modal(title,body,onSave){const wrap=document.createElement('div');wrap.className='native-overlay';const panel=document.createElement('section');panel.className='native-panel';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');const heading=document.createElement('h2');heading.textContent=title;const icon=document.createElement('button');icon.type='button';icon.className='native-close-icon';icon.setAttribute('aria-label','Close');icon.textContent='×';icon.onclick=()=>wrap.remove();panel.append(heading,icon);if(typeof body==='string'){const p=document.createElement('p');p.textContent=body;panel.append(p);}else panel.append(body);const actions=document.createElement('div');actions.className='native-actions';const close=document.createElement('button');close.type='button';close.textContent=onSave?'Cancel':'OK';close.className=onSave?'secondary':'primary';close.onclick=()=>wrap.remove();actions.append(close);if(onSave){const save=document.createElement('button');save.type='button';save.textContent='Save';save.className='primary';save.onclick=()=>{if(onSave()!==false)wrap.remove();};actions.append(save);}panel.append(actions);wrap.append(panel);document.body.append(wrap);(panel.querySelector('textarea,input')||close).focus();wrap.onkeydown=e=>{if(e.key==='Escape')wrap.remove();};return wrap;}
function renameProject(){
 const field=document.createElement('div');field.className='rename-field';field.innerHTML='<label for="rename-project-input">Project name</label>';
 const input=document.createElement('input');input.id='rename-project-input';input.value=state.projectName||'Lightweight Sunscreen Review';input.maxLength=80;field.append(input);
 const wrap=modal('Rename project',field,()=>{const value=input.value.trim();if(!value){input.setAttribute('aria-invalid','true');return false;}state.projectName=value;persist();show(root.dataset.screen);tell('Project name updated.');});
 wrap.querySelector('.native-panel').classList.add('rename-project-panel');
}
function installSidebarToggle(name){
 const ids={home:'17:75358','new-project':'25:81939',feedback:'16:73477',plan:'25:81381'},sidebar=node(ids[name]);if(!sidebar)return;
 sidebar.classList.add('app-sidebar');
 const toggle=()=>{state.sidebarCollapsed=!state.sidebarCollapsed;persist();adaptLayout(name);installSidebarToggle(name);};
 if(name==='home'||name==='new-project'){
  const old=leaf('Collapse Sidebar');if(old){let control=old;while(control.parentElement&&control.parentElement!==sidebar&&parseFloat(control.style.height||0)<32)control=control.parentElement;click(control,toggle,state.sidebarCollapsed?'Expand sidebar':'Collapse sidebar');}
 }else{
  const toggleIds={feedback:'16:73480',plan:'25:81384'},control=node(toggleIds[name]);click(control,toggle,state.sidebarCollapsed?'Expand sidebar':'Collapse sidebar');
 }
}
function setPlaybackTime(seconds,label){clock=seconds;const stage=root.querySelector('[data-name^="Main Video Stage"]'),video=stage?.querySelector('video');if(video)video.currentTime=seconds;root.querySelectorAll('p').forEach(p=>{if(/^00:\d{2}$/.test(p.textContent))p.textContent='00:'+String(seconds).padStart(2,'0');});updateTimeline(seconds,video?.duration||46.8);tell('Jumped to '+label+' · 00:'+String(seconds).padStart(2,'0'));}
function wireVersionAccordions(name){
 const cfg=name==='feedback'?{list:'16:73481',cards:['16:73482','16:73516','16:73527'],details:'16:73493'}:name==='plan'?{list:'25:81385',cards:['25:81386','25:81420','25:81431'],details:'25:81397'}:null;if(!cfg)return;
 const list=node(cfg.list),cards=cfg.cards.map(node);if(!list||cards.some(c=>!c))return;Object.assign(list.style,{display:'flex',flexDirection:'column',gap:'12px',overflowY:'auto'});
 cards.forEach((card,index)=>{const version=state.versions[index];card.style.display=version?'block':'none';if(!version)return;card.classList.toggle('active-version',index===state.currentVersion);Object.assign(card.style,{position:'relative',left:'auto',top:'auto',width:'196px',flex:'none',overflow:'hidden'});if(index===0){const detail=node(cfg.details),base=detail?.firstElementChild;if(base)base.classList.toggle('version-base-selected',index===state.currentVersion&&state.selected==null);if(detail)[...detail.querySelectorAll('p')].filter(p=>candidateNames.includes(p.textContent.trim())).forEach(p=>{let item=p;while(item.parentElement!==detail&&item.parentElement)item=item.parentElement;item.style.display=version.generated?'flex':'none';});}else{let options=card.querySelector('.version-candidates');if(!options){options=document.createElement('div');options.className='version-candidates';card.append(options);}options.replaceChildren();const base=document.createElement('button');base.type='button';base.className=index===state.currentVersion&&state.selected==null?'active':'';base.innerHTML='<span>'+version.base+'</span><small>Base</small>';base.onclick=e=>{e.stopPropagation();state.currentVersion=index;state.base=version.base;state.selected=null;persist();nav('feedback');};options.append(base);if(version.generated)candidateNames.forEach((title,i)=>{const item=document.createElement('button');item.type='button';item.className=index===state.currentVersion&&state.selected===i?'active':'';item.innerHTML='<span>'+title+'</span><small>'+String(index+1)+'-'+String.fromCharCode(65+i)+'</small>';item.onclick=e=>{e.stopPropagation();state.currentVersion=index;state.previewCandidate=i;state.selected=i;persist();nav('preview');};options.append(item);});}
  const header=[...card.querySelectorAll('p')].find(p=>p.textContent.trim()==='Version '+(index+1));if(header){let target=header.parentElement;while(target.parentElement&&target.parentElement!==card&&parseFloat(target.style.height||0)<38)target=target.parentElement;click(target,()=>{state.versionOpen[index]=!state.versionOpen[index];persist();render();},'Toggle Version '+(index+1));}
 });
 function render(){cards.forEach((card,index)=>{const version=state.versions[index];if(!version)return;const open=!!state.versionOpen[index],height=open?(version.generated?204:96):54;card.style.height=height+'px';card.setAttribute('aria-expanded',String(open));const detail=index===0?node(cfg.details):card.querySelector('.version-candidates');if(detail)detail.style.display=open?'flex':'none';const chevron=[...card.querySelectorAll('img')].find(img=>img.src.includes('svg'));if(chevron)chevron.closest('[class*="rotate"]')?.style.setProperty('rotate',open?'180deg':'0deg');});}
 render();
}
function wireCandidateSidebar(){
 const sidebar=node('14:73212'),toggle=node('14:73213'),tabs=node('14:73214');if(!sidebar||!toggle)return;
 click(toggle,()=>{state.candidateSidebarCollapsed=!state.candidateSidebarCollapsed;persist();adaptLayout('candidates');wireCandidateSidebar();},state.candidateSidebarCollapsed?'Expand sidebar':'Collapse sidebar');
 if(tabs)tabs.style.display=state.candidateSidebarCollapsed?'flex':'none';
 ['14:73215','14:73219','14:73223'].forEach((id,index)=>{const tab=node(id);if(tab)tab.style.display=index<state.versions.length?'flex':'none';});
 let newVersion=sidebar.querySelector('.candidate-new-version');if(!newVersion){newVersion=document.createElement('button');newVersion.type='button';newVersion.className='candidate-new-version';newVersion.textContent='New Version';newVersion.onclick=()=>beginNewVersion('Source Video');sidebar.append(newVersion);}newVersion.style.display=state.candidateSidebarCollapsed?'none':'flex';
 let expanded=sidebar.querySelector('.candidate-expanded-sidebar');if(!expanded){expanded=document.createElement('div');expanded.className='candidate-expanded-sidebar';sidebar.append(expanded);}expanded.style.display=state.candidateSidebarCollapsed?'none':'flex';expanded.replaceChildren();
 state.versions.forEach((version,index)=>{const card=document.createElement('section');card.className='candidate-version-card '+(index===state.currentVersion?'active':'');const header=document.createElement('button');header.type='button';header.className='candidate-version-heading';header.innerHTML='<span><strong>Version '+(index+1)+'</strong><small>'+(index===0?'2026-09-10 14:22:24':'Refined version')+'</small></span><b aria-hidden="true">⌃</b>';header.onclick=()=>{state.currentVersion=index;state.base=version.base;state.selected=null;persist();nav(version.generated?'candidates':'feedback');};const list=document.createElement('div');list.className='candidate-version-list';const entries=[[version.base,'Base'],...(version.generated?candidateNames.map((candidateName,candidate)=>[candidateName,`${index+1}-${String.fromCharCode(65+candidate)}`]):[])];entries.forEach(([label,badge],entryIndex)=>{const row=document.createElement('button'),active=index===state.currentVersion&&((entryIndex===0&&state.selected==null)||(entryIndex>0&&state.selected===entryIndex-1));row.type='button';row.className=(entryIndex===0?'source ':'')+(active?'active':'');row.innerHTML='<span>'+label+'</span><small>'+badge+'</small>';row.onclick=()=>{state.currentVersion=index;state.base=version.base;if(entryIndex){state.selected=entryIndex-1;state.previewCandidate=entryIndex-1;persist();nav('preview');}else{state.selected=null;persist();nav('feedback');}};list.append(row);});card.append(header,list);expanded.append(card);});
}
function wireFeedbackAccordions(){
 const sc=node('25:82580')?.querySelector('.cards-scroll'),shot2=node('25:82666'),shot4=node('25:82677');if(!sc||!shot2||!shot4)return;sc.classList.add('flow-scroll');let shot3=sc.querySelector('.shot3-clone');if(!shot3){shot3=shot2.cloneNode(true);shot3.classList.add('shot3-clone');shot3.querySelectorAll('[data-node-id]').forEach(el=>el.removeAttribute('data-node-id'));shot3.removeAttribute('data-node-id');const title=[...shot3.querySelectorAll('p')].find(p=>p.textContent.trim().startsWith('Shot 2:'));if(title)title.textContent='Shot 3: Soothing Benefits';const time=[...shot3.querySelectorAll('p')].find(p=>p.textContent.trim()==='(00:12–00:25)');if(time)time.textContent='(00:25–00:34)';sc.insertBefore(shot3,shot4);}const cards=[node('25:82631'),node('25:82646'),shot2,shot3,shot4];if(cards.some(c=>!c))return;
 const content=[
  {title:'Whole Video',time:'',description:'A creator recommends a high-protection sunscreen, highlights its lightweight and hydrating feel, supports the claim with a Lijiang travel experience, then closes with soothing, sensitive-skin and reef-friendly benefits.',question:'How does the video feel overall?',options:['Feels information-heavy','Pacing feels rushed','Claims need clearer proof']},
  {title:'Shot 1: Fresh Feel + SPF50+',time:'(00:00–00:12)',description:'The creator opens with a strong recommendation, contrasts SPF50+ PA++++ protection with a fresh, non-greasy feel, and quickly stacks the core product benefits.',question:'Anything you’d like to change here?',options:['Too many benefits arrive at once','The SPF rating is hard to catch','The hook feels too absolute']},
  {title:'Shot 2: Lijiang Proof',time:'(00:12–00:25)',description:'The creator uses a high-UV trip to Lijiang as personal proof, saying consistent use helped prevent sunburn and tanning.',question:'How does the personal proof feel?',options:['The travel story feels compressed','The result needs more context']},
  {title:'Shot 3: Soothing Benefits',time:'(00:25–00:34)',description:'The creator groups centella, soothing care, a low-irritation formula, and the allergy-return promise into a rapid sequence of supporting benefits.',question:'How does the supporting evidence feel?',options:['The ingredient claims move too quickly','The sensitive-skin benefit needs emphasis']},
  {title:'Shot 4: Reef-Friendly Close',time:'(00:34–00:47)',description:'The creator adds a reef-friendly claim, recommends the sunscreen for beach trips, and closes with Korean retail popularity as social proof.',question:'How does the ending feel?',options:['The environmental claim feels abrupt','The ending packs in too many claims']}
 ];
 const appendOption=(options,text)=>{const option=document.createElement('button');option.type='button';option.className='feedback-option';option.textContent=text;option.classList.toggle('chosen',state.feedback.includes(text));option.onclick=e=>{e.stopPropagation();const selected=state.feedback.includes(text);state.feedback=selected?state.feedback.filter(value=>value!==text):[...state.feedback,text];option.classList.toggle('chosen',!selected);persist();updateFeedbackCount();};options.append(option);};
 const addFeeling=(index,options)=>{const input=document.createElement('textarea');input.placeholder='Tell me what you’d like to change';input.value=state.note||'';input.oninput=()=>{state.note=input.value;persist();};modal('Add my own feelings',input,()=>{const value=input.value.trim();if(!value)return false;if(!state.customFeelings[index].includes(value))state.customFeelings[index].push(value);if(!state.feedback.includes(value))state.feedback.push(value);state.note='';appendOption(options,value);persist();updateFeedbackCount();tell('Your thought has been added.');});};
 cards.forEach((card,index)=>{const item=content[index],header=document.createElement('button'),body=document.createElement('div'),originalIcon=card.firstElementChild?.firstElementChild?.firstElementChild?.cloneNode(true);card.replaceChildren();card.classList.add('feedback-card');header.type='button';header.className='feedback-card-header';header.setAttribute('aria-label','Toggle '+item.title);header.innerHTML='<span class="feedback-card-heading"><span class="feedback-card-icon"></span><span class="feedback-card-title"></span><span class="feedback-card-time"></span></span><span class="feedback-card-chevron" aria-hidden="true"></span>';const iconHost=header.querySelector('.feedback-card-icon');if(originalIcon)iconHost.append(originalIcon);header.querySelector('.feedback-card-title').textContent=item.title;header.querySelector('.feedback-card-time').textContent=item.time;body.className='feedback-card-body';const description=document.createElement('p');description.className='feedback-card-description';description.textContent=item.description;const divider=document.createElement('div');divider.className='feedback-card-divider';const question=document.createElement('p');question.className='feedback-card-question';question.textContent='🤔 '+item.question;const options=document.createElement('div');options.className='feedback-card-options';[...item.options,...state.customFeelings[index]].forEach(text=>appendOption(options,text));const add=document.createElement('button');add.type='button';add.className='feedback-card-add';add.textContent='＋ Add my own feelings';add.onclick=e=>{e.stopPropagation();addFeeling(index,options);};body.append(description,divider,question,options,add);card.append(header,body);header.onclick=()=>{state.shotOpen[index]=!state.shotOpen[index];persist();render();};});
 function render(){cards.forEach((card,index)=>{const open=!!state.shotOpen[index],body=card.querySelector('.feedback-card-body'),header=card.querySelector('.feedback-card-header'),chevron=card.querySelector('.feedback-card-chevron');card.classList.toggle('is-open',open);card.setAttribute('aria-expanded',String(open));header?.setAttribute('aria-expanded',String(open));if(body)body.hidden=!open;if(chevron)chevron.textContent=open?'⌃':'⌄';});}
 render();
}
function wirePreviewPager(){
 const pager=node('14:73237');if(!pager)return;
 const previousIcon=node('14:73238')?.querySelector('img')?.cloneNode(true),nextIcon=node('14:73240')?.querySelector('img')?.cloneNode(true);
 const previous=document.createElement('button'),count=document.createElement('span'),next=document.createElement('button');
 previous.type=next.type='button';previous.className='preview-pager-button';next.className='preview-pager-button';count.className='preview-pager-count';
 previous.setAttribute('aria-label','Previous candidate');next.setAttribute('aria-label','Next candidate');
 if(previousIcon)previous.append(previousIcon);else previous.textContent='‹';if(nextIcon)next.append(nextIcon);else next.textContent='›';
 count.textContent=((state.previewCandidate??state.selected??0)+1)+'/3';pager.replaceChildren(previous,count,next);pager.classList.add('preview-pager');
 previous.onclick=()=>{state.previewCandidate=(state.previewCandidate+2)%3;persist();show('preview');};
 next.onclick=()=>{state.previewCandidate=(state.previewCandidate+1)%3;persist();show('preview');};
}
function wirePreviewAccordions(){const scroll=node('14:73245')?.querySelector('.cards-scroll'),cards=['14:73296','14:73311','14:73331','14:73406','16:73462'].map(node).filter(Boolean);if(!scroll||cards.length!==5)return;scroll.classList.add('preview-cards-scroll');cards.forEach((card,index)=>{card.classList.add('preview-shot-card');const header=card.firstElementChild;header?.classList.add('preview-shot-header');const titleRow=header?.firstElementChild;if(index===0&&titleRow&&!titleRow.querySelector('.preview-whole-icon')){const icon=document.createElement('span');icon.className='preview-whole-icon';icon.setAttribute('aria-hidden','true');icon.innerHTML='<svg viewBox="0 0 16 18" fill="none"><rect x="3" y="1.5" width="10" height="15" rx="1.5" stroke="currentColor" stroke-width="1.5"/><rect x="5.5" y="4.5" width="5" height="1.5" rx=".75" fill="currentColor"/><rect x="5.5" y="8" width="5" height="5.5" rx=".75" stroke="currentColor" stroke-width="1.25"/></svg>';titleRow.prepend(icon);}if(header){click(header,()=>{state.previewShotOpen[index]=!state.previewShotOpen[index];persist();render();},'Toggle preview '+(index?`Shot ${index}`:'Whole Video'));} });function render(){cards.forEach((card,index)=>{const open=!!state.previewShotOpen[index];card.classList.toggle('is-open',open);card.setAttribute('aria-expanded',String(open));[...card.children].slice(1).forEach(child=>child.hidden=!open);const chevron=card.firstElementChild?.lastElementChild;if(chevron)chevron.style.rotate=open?'0deg':'180deg';});}render();}
function updateFeedbackCount(){root.querySelectorAll('p').forEach(p=>{if(/^\d+ thoughts added$/.test(p.textContent))p.textContent=state.feedback.length+' thoughts added';});}
function showGeneratingState(){
 const duration=12000,elapsed=Date.now()-state.generationStartedAt;if(elapsed>=duration){state.generating=false;state.versions[state.currentVersion].generated=true;persist();show('candidates');return;}
 const thoughts=['Reviewing the confirmed change plan','Mapping each change to the relevant shots','Building three distinct editing directions','Rendering pacing, action, and story variations','Checking each candidate against the original feedback'];
 const agent=node('14:72183'),agentIcon=node('14:72206')?.cloneNode(true);if(agent){agent.classList.add('generation-agent');agent.innerHTML='<div class="agent-thinking"><div class="agent-thinking-title"><span class="thinking-orb"></span><strong>Video Agent is working</strong><span class="thinking-dots"><i></i><i></i><i></i></span></div><p class="agent-thinking-current"></p><div class="agent-thinking-log"></div></div>';if(agentIcon)agent.querySelector('.thinking-orb').append(agentIcon);}
 ['14:72235','14:72276','14:72317'].forEach((id,index)=>{const card=node(id);if(!card)return;card.classList.add('generation-placeholder');card.setAttribute('aria-busy','true');card.innerHTML='<div class="generation-glow glow-'+index+'"></div><div class="generation-skeleton"><span></span><span></span><span></span><div></div></div><p>Generating candidate '+String.fromCharCode(65+index)+'…</p>';});
 const footer=node('14:72384');if(footer)footer.style.visibility='hidden';
 const tick=()=>{if(root.dataset.screen!=='candidates'||!state.generating)return;const passed=Date.now()-state.generationStartedAt,index=Math.min(thoughts.length-1,Math.floor(passed/2200)),current=root.querySelector('.agent-thinking-current'),log=root.querySelector('.agent-thinking-log');if(current)current.textContent=thoughts[index]+'…';if(log)log.textContent=index?thoughts.slice(0,index).join('  ·  '):'Preparing the workspace';if(passed>=duration){state.generating=false;state.versions[state.currentVersion].generated=true;persist();show('candidates');return;}generationTimer=setTimeout(tick,700);};tick();
}
function beginNewVersion(base='Source Video'){const next={base,generated:false};if(state.versions.length<3){state.versions.push(next);state.currentVersion=state.versions.length-1;}else{state.currentVersion=state.versions.length-1;state.versions[state.currentVersion]=next;}state.base=base;state.selected=null;state.feedback=[];state.customFeelings=[[],[],[],[],[]];state.choices=[null,null];state.customDirections=[[],[]];state.skipped=[false,false];state.previewShotOpen=[true,false,false,false,false];state.planVersion=null;state.versionOpen[state.currentVersion]=true;persist();nav('feedback');}
function startGeneration(){if(!state.choices.every((choice,index)=>choice!=null||state.skipped[index]))return;state.rounds.push({version:state.currentVersion,base:state.base,feedback:[...state.feedback],choices:[...state.choices],created:Date.now()});state.selected=null;state.generating=false;state.versions[state.currentVersion].generated=true;persist();transitionTo('candidates');}
function inputAt(text,placeholder,value,change){const el=leaf(text);if(!el)return;const inp=document.createElement('input');inp.className='inline-input';inp.placeholder=placeholder;inp.value=value||'';inp.setAttribute('aria-label',placeholder);inp.oninput=()=>change(inp.value);el.replaceChildren(inp);return inp;}
function scrollCards(screen){const config=screen==='feedback'?['25:82580',110,690,['25:82631','25:82646','25:82666','25:82677']]:screen==='plan'?['11:68704',91,690,['11:68755','13:69198']]:screen==='preview'?['14:73245',98,716,['14:73296','14:73311','14:73331','14:73406','16:73462']]:null;if(!config)return;const [id,start,end,ids]=config,parent=node(id),sc=document.createElement('div');sc.className='cards-scroll';Object.assign(sc.style,{position:'absolute',left:'0',top:start+'px',width:'100%',height:(end-start)+'px',overflowY:'auto',scrollbarWidth:'none'});parent.append(sc);ids.forEach(id=>{const el=node(id);if(!el)return;el.style.top=(parseFloat(el.style.top)-start)+'px';sc.append(el);});if(screen==='plan'){sc.classList.add('flow-scroll');sc.querySelectorAll(':scope > [data-node-id]').forEach(el=>Object.assign(el.style,{position:'relative',left:'auto',top:'auto',width:'100%',flex:'none'}));}}
function wire(name){
 const backgrounds={feedback:'25:82581',plan:'11:68705',candidates:'14:72184'};if(backgrounds[name]){const bg=node(backgrounds[name]);bg.replaceChildren();bg.style.background='url(assets/backdrop-'+name+'.png) left top / 100% 100% no-repeat';bg.style.border=0;}
 scrollCards(name);
 installSidebarToggle(name);
 if(name==='candidates')wireCandidateSidebar();
 wireVersionAccordions(name);
 button('TikTok Shop Video Studio',()=>nav('home'));
 if(name==='home'||name==='new-project'){
  if(name==='home')button('Start Refining',()=>nav('new-project'));
  const titles=['Lightweight Sunscreen Review','Everyday Lip Tint','Weekend Sneaker Edit','Morning Coffee Routine','Travel Skincare Essentials'];
  titles.forEach((text,index)=>{const el=leaf(text);if(!el)return;if(index===0&&state.projectName&&state.projectName!==text)el.textContent=state.projectName;let card=el;while(card.parentElement&&parseFloat(card.style.height||0)<90)card=card.parentElement;card.classList.toggle('project-unavailable',index>0);if(index>0)card.setAttribute('aria-description','Temporarily unavailable');click(card,()=>{if(index===0){state.projectName=el.textContent.trim();persist();nav('feedback');}else tell('暂时无法体验，请体验第一个项目');},'Open '+text);});
  inputAt('Search project name','Search project name','',value=>{titles.forEach(t=>{const el=leaf(t);if(!el)return;let card=el;while(card.parentElement&&parseFloat(card.style.height||0)<90)card=card.parentElement;card.style.visibility=t.toLowerCase().includes(value.toLowerCase())?'visible':'hidden';});});
  button('Video Refining',()=>nav('home'));
  root.querySelectorAll('[data-name="semi-icons-Star_stroked"]').forEach(el=>click(el,()=>{el.style.opacity=el.style.opacity==='0.4'?'1':'0.4';},'Toggle favorite'));
 }
 if(name==='new-project'){
  inputAt('Please enter','Please enter',state.newName||'',v=>{state.newName=v;persist();});
  button('Cancel',()=>nav('home'));root.querySelectorAll('[data-name="semi-icons-close"]').forEach(el=>click(el,()=>nav('home'),'Close'));
  const target=leaf('Click to Upload File or Drag File to here');const area=target?.closest('[data-name="Content"]')||target?.parentElement?.parentElement;
  const file=document.createElement('input');file.type='file';file.accept='.mp4,video/mp4';file.hidden=true;file.id='video-upload';root.append(file);
  const take=f=>{if(!f)return;if(!/\.mp4$/i.test(f.name)){tell('Only .mp4 files are supported.');return;}selectedFile=f;if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=URL.createObjectURL(f);if(target)target.textContent=f.name;};file.onchange=()=>take(file.files[0]);click(area,()=>file.click(),'Upload video');if(area){area.ondragover=e=>e.preventDefault();area.ondrop=e=>{e.preventDefault();take(e.dataTransfer.files[0]);};}
  button('Create',()=>tell('暂时无法创建，可以体验我们这一个案例项目'));
 }
 if(['feedback','plan'].includes(name)){
  const projectTitle=leaf('Lightweight Sunscreen Review');if(projectTitle){projectTitle.textContent=state.projectName||'Lightweight Sunscreen Review';click(projectTitle,renameProject,'Rename project');const edit=projectTitle.nextElementSibling;click(edit,renameProject,'Rename project');}
  candidateNames.forEach((text,i)=>button(text,()=>{state.selected=i;persist();nav('preview');}));
  button('New Version',()=>beginNewVersion('Source Video'));
  root.querySelectorAll('[data-name="Button_Borderless"]').forEach(el=>{if(el.querySelector('img')?.src.includes('svg')&&parseFloat(el.style.width)===32&&el.parentElement.dataset.nodeId?.includes('67505'))click(el,()=>nav('home'),'Back to projects');});
 }
 if(name==='feedback'){
  wireFeedbackAccordions();
  button('Let’s Plan the Changes',()=>{persist();transitionTo('plan');});
  button('View Details',()=>{const box=document.createElement('div');box.className='thought-groups';feedbackSections.forEach((section,index)=>{const selected=[...section.options,...(state.customFeelings[index]||[])].filter(value=>state.feedback.includes(value));if(!selected.length)return;const group=document.createElement('section'),heading=document.createElement('h3'),list=document.createElement('ul');heading.textContent=section.title;selected.forEach(value=>{const item=document.createElement('li');item.textContent=value;list.append(item);});group.append(heading,list);box.append(group);});if(!box.children.length){const empty=document.createElement('p');empty.className='thoughts-empty';empty.textContent='No feelings selected yet.';box.append(empty);}modal('Your thoughts',box);});
  root.querySelectorAll('[data-name="Tag Radio"]').forEach(el=>{const text=el.textContent.trim(),selected=state.feedback.includes(text);el.classList.toggle('chosen',selected);el.classList.toggle('unchosen',!selected);click(el,()=>{const has=state.feedback.includes(text);state.feedback=has?state.feedback.filter(t=>t!==text):[...state.feedback,text];el.classList.toggle('chosen',!has);el.classList.toggle('unchosen',has);updateFeedbackCount();persist();},text);});updateFeedbackCount();
  [...root.querySelectorAll('p')].filter(p=>p.textContent==='Add my own feelings').forEach(el=>click(el.parentElement,()=>{const input=document.createElement('textarea');input.placeholder='Tell me what you’d like to change';input.value=state.note||'';input.oninput=()=>{state.note=input.value;persist();};modal('Add my own feelings',input,()=>{if(!input.value.trim())return false;state.feedback.push(input.value.trim());state.note='';persist();tell('Your thought has been added.');});},'Add my own feelings'));
 }
 if(name==='plan'){
  if(state.planVersion!==state.currentVersion){state.choices=[null,null];state.customDirections=[[],[]];state.skipped=[false,false];state.plannedChanges=[...plannedDefaults];state.planVersion=state.currentVersion;persist();}
  button('Back to Feedback',()=>nav('feedback'));
  let generateButton;const updateGenerate=()=>{const ready=state.choices.every((choice,index)=>choice!=null||state.skipped[index]);if(generateButton){generateButton.classList.toggle('action-disabled',!ready);generateButton.setAttribute('aria-disabled',String(!ready));generateButton.style.pointerEvents=ready?'auto':'none';}}
  const labels=['Lead with the lightweight feel','Open with the protection rating','Give the Lijiang proof more space','Shorten the story and state the result'];
  labels.forEach((text,i)=>{const el=leaf(text);if(!el)return;let card=el;while(card.parentElement&&parseFloat(card.style.height||0)<40)card=card.parentElement;const group=Math.floor(i/2),choice=i%2;card.dataset.questionGroup=group;card.classList.toggle('chosen',state.choices[group]===choice);card.classList.toggle('unchosen',state.choices[group]!==choice);click(card,()=>{if(state.skipped[group])return;state.choices[group]=choice;persist();show('plan');},text);});
  const groups=[node('11:68762'),node('13:69042')],containers=[node('11:68765'),node('13:69046')];containers.forEach((container,group)=>{const actions=container?.children[2];(state.customDirections[group]||[]).forEach((value,index)=>{const option=document.createElement('button');option.type='button';option.className='custom-direction-option '+(state.choices[group]==='custom-'+index?'chosen':'unchosen');option.dataset.questionGroup=group;option.style.top=(110+index*55)+'px';option.innerHTML='<b>'+String.fromCharCode(67+index)+'.</b><span><strong>'+value+'</strong><small>Your direction</small></span>';option.onclick=()=>{state.choices[group]='custom-'+index;persist();show('plan');};container.insertBefore(option,actions);});});
  const adds=[...root.querySelectorAll('p')].filter(el=>el.textContent==='Add my own direction');adds.forEach((el,i)=>click(el.parentElement,()=>{if(state.skipped[i])return;const input=document.createElement('textarea');input.placeholder='Describe your direction';modal('Add my own direction',input,()=>{const value=input.value.trim();if(!value)return false;state.customDirections[i].push(value);state.choices[i]='custom-'+(state.customDirections[i].length-1);persist();show('plan');});},'Add my own direction'));
  const skips=[...root.querySelectorAll('p')].filter(el=>el.textContent==='Skip question');function questionHeight(i){return state.skipped[i]?(i===0?43:76):(i===0?153:169.5)+(state.customDirections[i]?.length||0)*55;}function renderSkip(i){const skipped=!!state.skipped[i],customCount=state.customDirections[i]?.length||0;root.querySelectorAll('[data-question-group="'+i+'"]').forEach(card=>card.style.display=skipped?'none':'flex');const add=adds[i]?.parentElement;if(add){add.classList.toggle('direction-disabled',skipped);add.setAttribute('aria-disabled',String(skipped));}if(skips[i])skips[i].textContent=skipped?'Cancel skip':'Skip question';const content=groups[i]?.children[1],actions=content?.children[content.children.length-1];if(groups[i])groups[i].style.height=questionHeight(i)+'px';if(actions)actions.style.top=skipped?'0px':(110+customCount*55)+'px';const h1=questionHeight(0),h2=questionHeight(1);if(groups[1])groups[1].style.top=(54+h1+16)+'px';const questions=node('11:68755');if(questions)questions.style.height=(54+h1+16+h2+16)+'px';updateGenerate();}skips.forEach((el,i)=>click(el.parentElement,()=>{state.skipped[i]=!state.skipped[i];if(state.skipped[i])state.choices[i]=null;persist();show('plan');},'Skip or restore question '+(i+1)));skips.forEach((_,i)=>renderSkip(i));
  const changesWrap=node('13:69287'),planned=node('13:69198');if(changesWrap){changesWrap.replaceChildren();Object.assign(changesWrap.style,{display:'flex',flexDirection:'column',gap:'8px',height:'auto'});state.plannedChanges.forEach((value,index)=>{const item=document.createElement('button');item.type='button';item.className='planned-change-item';item.innerHTML='<span>'+value+'</span><small>Shot'+(index+1)+'</small>';item.onclick=e=>{e.stopPropagation();document.querySelector('.plan-item-menu')?.remove();const menu=document.createElement('div');menu.className='plan-item-menu';menu.innerHTML='<button type="button" class="edit">Edit</button><button type="button" class="delete">Delete</button>';const rect=item.getBoundingClientRect();Object.assign(menu.style,{left:Math.min(rect.right-112,innerWidth-124)+'px',top:Math.min(rect.bottom+6,innerHeight-92)+'px'});menu.querySelector('.edit').onclick=event=>{event.stopPropagation();menu.remove();const input=document.createElement('textarea');input.value=value;input.placeholder='Describe this planned change';modal('Edit planned change',input,()=>{const edited=input.value.trim();if(!edited)return false;state.plannedChanges[index]=edited;persist();show('plan');});};menu.querySelector('.delete').onclick=event=>{event.stopPropagation();state.plannedChanges.splice(index,1);persist();menu.remove();show('plan');};document.body.append(menu);setTimeout(()=>addEventListener('click',event=>{if(!menu.contains(event.target))menu.remove();},{once:true}),0);};changesWrap.append(item);});if(planned)planned.style.height=(51+changesWrap.scrollHeight+12)+'px';}root.querySelectorAll('p').forEach(p=>{if(/Planned Changes$/.test(p.textContent.trim()))p.textContent='🎯 '+state.plannedChanges.length+' Planned Changes';});
  [...root.querySelectorAll('p')].filter(p=>/^Shot[1-4]$/.test(p.textContent.trim())).forEach(p=>{const shot=Number(p.textContent.trim().slice(4)),times={1:0,2:12,3:25,4:34};click(p.parentElement,()=>setPlaybackTime(times[shot],'Shot '+shot),'Jump to Shot '+shot);});
  generateButton=button('Generate New Videos',startGeneration);updateGenerate();
 }
 if(name==='candidates'){
  click(node('25:81489'),()=>nav('home'),'Back to projects');
  const projectTitle=leaf('Lightweight Sunscreen Review');if(projectTitle){projectTitle.textContent=state.projectName||'Lightweight Sunscreen Review';click(projectTitle,renameProject,'Rename project');click(projectTitle.nextElementSibling,renameProject,'Rename project');}
  const cardIds=['14:72235','14:72276','14:72317'];
  let refineButton,exportButton;const renderCandidateSelection=()=>{cardIds.forEach((id,i)=>node(id)?.classList.toggle('candidate-selected',state.selected===i));const enabled=state.selected!=null;[refineButton,exportButton].forEach(control=>{if(!control)return;control.classList.toggle('action-disabled',!enabled);control.setAttribute('aria-disabled',String(!enabled));control.style.pointerEvents=enabled?'auto':'none';});};
  cardIds.forEach((id,i)=>{const card=node(id),head=node(['14:72236','14:72277','14:72318'][i]);if(!card)return;click(card,()=>{if(state.generating)return;state.selected=i;persist();renderCandidateSelection();},'Select candidate '+String.fromCharCode(65+i));if(head&&!head.querySelector('.candidate-detail')){const detail=document.createElement('button');detail.type='button';detail.className='candidate-detail';detail.setAttribute('aria-label','View Detail for candidate '+String.fromCharCode(65+i));detail.innerHTML='<span>Detail</span><img src="assets/detail-arrow.svg" alt="">';detail.onclick=e=>{e.stopPropagation();state.previewCandidate=i;persist();nav('preview');};head.append(detail);}});
  [...root.querySelectorAll('[data-name^="Central Floating Play"]')].filter(el=>!el.dataset.name.endsWith(':shadow')).forEach((el,i)=>click(el,()=>{state.previewCandidate=i;persist();nav('preview');},'Preview candidate '+String.fromCharCode(65+i)));
  refineButton=button('Refine Candidate',refine);button('Back to Feedback',()=>nav('feedback'));exportButton=button('Export Video',()=>modal('Export Video','This prototype contains the Figma preview images. A playable candidate video is needed to export the actual result.'));['V1','V2','V3'].forEach((t,index)=>button(t,()=>{if(index>=state.versions.length)return;state.currentVersion=index;state.selected=null;persist();nav(state.versions[index].generated?'candidates':'feedback');}));renderCandidateSelection();
  if(state.generating)showGeneratingState();
 }
 if(name==='preview'){
  button('Back',()=>nav('candidates'));button('Refine in a new version',refine);
  wirePreviewPager();
  {const candidate=state.previewCandidate??state.selected??0;const t=node('14:73393'),d=node('14:73395');if(t)t.textContent='Candidate '+String(state.currentVersion+1)+'-'+String.fromCharCode(65+candidate)+': '+candidateNames[candidate];if(d)d.textContent=candidateDescriptions[candidate];const count=root.querySelector('.preview-pager-count');if(count)count.textContent=(candidate+1)+'/3';}wirePreviewAccordions();
 }
 if(['feedback','plan','preview'].includes(name)){
  root.querySelectorAll('[data-name^="Central Floating Play"]').forEach(el=>{if(el.dataset.name.endsWith(':shadow'))return;click(el,()=>togglePlayback(el),'Play or pause video');});
  root.querySelectorAll('[data-name="Button"]').forEach(el=>{if(el.querySelector('img')&&parseFloat(el.style.width)===16)click(el,()=>togglePlayback(el),'Video playback control');});
 }
 if(name!=='candidates')button('Export Video',()=>modal('Export Video','This prototype contains the Figma preview images. A playable candidate video is needed to export the actual result.'));
}
function refine(){const candidate=state.selected??state.previewCandidate;if(candidate==null)return;const base=candidateNames[candidate];state.previewCandidate=candidate;beginNewVersion(base);}
function togglePlayback(el){const stage=el?.closest?.('[data-name^="Main Video Stage"]')||root.querySelector('[data-name^="Main Video Stage"]'),video=el?.matches?.('video')?el:stage?.querySelector('.demo-video');if(video){root.querySelectorAll('.demo-video').forEach(other=>{if(other!==video)other.pause();});if(video.paused){video.play().catch(()=>syncCentralPlay(video));playing=video;tell('Playing source video');}else{video.pause();playing=null;tell('Paused');}syncCentralPlay(video);return;}tell('Video preview is unavailable.');}
addEventListener('resize',scale);addEventListener('hashchange',()=>{clearTransition();show(location.hash.slice(1));});show(location.hash.slice(1)||'home');
