const root=document.getElementById('design');
async function show(name){const allowed=['home','new-project','feedback','plan','candidates','preview'];if(!allowed.includes(name))name='home';root.innerHTML=await(await fetch('screens/'+name+'.html')).text();await geometry(name);root.dataset.screen=name;wire(name);document.title='TikTok Shop Video Studio';scale();}
function setSize(el,width,height){if(!el)return;if(width!=null)el.style.width=typeof width==='number'?width+'px':width;if(height!=null)el.style.height=typeof height==='number'?height+'px':height;}
function fitWorkspace(main,video,panel,baseWidth,baseHeight){
 if(!main||!video||!panel)return;
 const mainWidth=main.getBoundingClientRect().width||parseFloat(main.style.width)||1220;
 const mainHeight=main.getBoundingClientRect().height||parseFloat(main.style.height)||784;
 const availableHeight=Math.max(480,mainHeight-32);
 const maxVideoWidth=Math.max(360,mainWidth-32-420-16);
 const ratio=Math.min(availableHeight/baseHeight,maxVideoWidth/baseWidth);
 const visualWidth=Math.round(baseWidth*ratio);
 const visualHeight=Math.round(baseHeight*ratio);
 const panelHeight=availableHeight;
 const fittedBaseHeight=panelHeight/ratio;Object.assign(video.style,{width:baseWidth+'px',height:fittedBaseHeight+'px',left:'16px',top:'16px',transform:`scale(${ratio})`,transformOrigin:'top left',overflow:'hidden'});
 if(fittedBaseHeight>baseHeight+1){const stage=[...video.querySelectorAll('[data-name^="Main Video Stage"]')].find(el=>!el.dataset.name.includes('Timeline')),stageShell=stage?.parentElement,body=stageShell?.closest('[data-node-id]');if(stage&&body){const bodyHeight=fittedBaseHeight-81,stageHeight=bodyHeight-32;body.style.setProperty('height',bodyHeight+'px','important');Object.assign(stage.style,{position:'absolute',left:'0px',top:'0px',height:stageHeight+'px',minHeight:'0',overflow:'hidden'});const portrait=stage.querySelector(':scope > [data-node-id]');if(portrait)Object.assign(portrait.style,{height:'100%',width:'auto',left:'50%',transform:'translateX(-50%)'});const play=[...stage.querySelectorAll('[data-name^="Central Floating Play"]')].find(el=>!el.dataset.name.endsWith(':shadow'));if(play)Object.assign(play.style,{left:'50%',top:'50%'});const timeline=body.querySelector('[data-name^="Shot Timeline Track"]');if(timeline)Object.assign(timeline.style,{position:'absolute',left:'0px',top:(stageHeight+16)+'px'});}}
 Object.assign(panel.style,{left:(32+visualWidth)+'px',top:'16px',width:Math.max(360,mainWidth-48-visualWidth)+'px',height:panelHeight+'px',transform:'none'});
 const panelBackground=panel.firstElementChild;if(panelBackground)Object.assign(panelBackground.style,{inset:'0px',width:'100%',height:'100%'});
 panel.querySelectorAll(':scope > [data-node-id], :scope > .cards-scroll').forEach(el=>{if(el.classList.contains('cards-scroll'))return;const left=parseFloat(el.style.left||0),elementHeight=parseFloat(el.style.height||0);if(left<=20)el.style.width=left===0?'100%':'calc(100% - 32px)';if(left<=0&&elementHeight>=56&&elementHeight<=70){el.style.left='-1px';el.style.top='auto';el.style.bottom='-1px';el.style.width='calc(100% + 2px)';}});
 const sc=panel.querySelector('.cards-scroll');if(sc){const scTop=parseFloat(sc.style.top)||110;sc.style.width='100%';sc.style.height=Math.max(120,panelHeight-scTop-62)+'px';sc.querySelectorAll(':scope > [data-node-id]').forEach(el=>el.style.width=sc.classList.contains('flow-scroll')?'100%':'calc(100% - 32px)');}
}
function fitFeedbackContent(panel){
 if(!panel)return;
 const header=node('25:82600'),headerInner=node('25:82601'),steps=node('25:82617'),intro=node('25:82623'),introText=node('25:82630');if(header)header.style.width='calc(100% - 32px)';if(headerInner)headerInner.style.width='100%';if(steps)Object.assign(steps.style,{left:'auto',right:'0px',transform:'scale(.82)',transformOrigin:'right center'});if(intro)intro.style.width='100%';if(introText)introText.style.width='100%';
 const cards=[{card:'25:82631',header:'25:82632',title:'25:82633',chevron:'25:82636',description:'25:82637',question:'25:82638',prompt:'25:82639',options:'25:82641',add:'25:82645'},{card:'25:82646',header:'25:82647',title:'25:82648',chevron:'25:82656',description:'25:82657',question:'25:82658',prompt:'25:82659',options:'25:82661',add:'25:82665'}];
 cards.forEach((cfg,index)=>{const card=node(cfg.card),head=node(cfg.header),title=node(cfg.title),chevron=node(cfg.chevron),description=node(cfg.description),question=node(cfg.question),prompt=node(cfg.prompt),options=node(cfg.options),add=node(cfg.add);if(!card)return;if(head)head.style.width='calc(100% - 24px)';if(title)title.style.width='calc(100% - 24px)';if(chevron)Object.assign(chevron.style,{left:'auto',right:'0px'});if(description)description.style.width='calc(100% - 24px)';if(question)Object.assign(question.style,{width:'calc(100% - 24px)',height:'auto',display:'flex',flexDirection:'column',gap:'10px',alignItems:'flex-start',paddingTop:'12px'});if(prompt)Object.assign(prompt.style,{position:'relative',left:'auto',top:'auto',width:'100%',height:'auto'});if(options){Object.assign(options.style,{position:'relative',left:'auto',top:'auto',width:'100%',height:'auto',display:'flex',flexWrap:'wrap',gap:'8px'});[...options.children].forEach(option=>Object.assign(option.style,{position:'relative',left:'auto',top:'auto'}));}if(add)Object.assign(add.style,{position:'relative',left:'auto',top:'auto'});if(state.shotOpen[index]&&question){const needed=113+question.scrollHeight+16;card.style.height=Math.max(index?261:223,needed)+'px';}});
 const footer=node('25:82688'),footerInfo=node('25:82689'),footerButton=node('25:82692'),panelWidth=panel.getBoundingClientRect().width;if(footer)footer.style.width='calc(100% + 2px)';if(footerInfo){footerInfo.style.left='16px';footerInfo.style.display=panelWidth<420?'none':'flex';}if(footerButton)Object.assign(footerButton.style,{left:'auto',right:'16px'});
}
function fitPlanContent(panel){
 if(!panel)return;
 const available='calc(100% - 22px)';
 const header=node('11:68725'),steps=node('11:68865');if(header)header.style.width='100%';if(steps)Object.assign(steps.style,{left:'auto',right:'0px',transform:'scale(.74)',transformOrigin:'right center'});
 const questions=node('11:68755'),groups=[node('11:68762'),node('13:69042')],containers=[node('11:68765'),node('13:69046')];
 if(questions)questions.style.width='100%';
 groups.forEach(group=>{if(group)group.style.width=available;});
 containers.forEach(container=>{if(container)container.style.width='100%';});
 panel.querySelectorAll('[data-name="Tag Radio"]').forEach(option=>option.style.width='100%');
 [node('11:68756'),node('11:68757'),node('13:69199'),node('13:69200')].forEach(el=>{if(el)el.style.width='100%';});
 const planned=node('13:69198');if(planned)planned.style.width='100%';
 const footer=node('11:68810'),actions=node('13:69323'),status=node('11:68811');
 if(footer)footer.style.width='calc(100% + 2px)';
 if(actions)Object.assign(actions.style,{left:'auto',right:'16px'});
 if(status)status.style.display=panel.getBoundingClientRect().width<520?'none':'flex';
}
function adaptLayout(name){
 const width=Math.max(innerWidth,768),height=innerHeight,collapsed=!!state.sidebarCollapsed,sidebarWidth=collapsed?56:220;
 const screen=root.firstElementChild;setSize(root,width,height);setSize(screen,width,height);root.style.transform='none';
 const viewport=document.getElementById('viewport');viewport.style.height='100vh';viewport.style.width='100vw';
 const configs={
  home:{content:'17:75425',sidebar:'17:75358',main:'17:75178',offset:52},
  'new-project':{content:'25:81938',sidebar:'25:81939',main:'25:81991',offset:52},
  feedback:{content:'11:65311',sidebar:'16:73477',main:'11:65374',offset:116,video:'11:65375',panel:'25:82580',vw:631,vh:752},
  plan:{content:'11:68602',sidebar:'25:81381',main:'11:68665',offset:116,video:'11:68666',panel:'11:68704',vw:631,vh:752}
 };
 const c=configs[name];
 if(c){
  const content=node(c.content),sidebar=node(c.sidebar),main=node(c.main);setSize(content,width,height-c.offset);setSize(sidebar,sidebarWidth,height-c.offset);setSize(main,width-sidebarWidth,height-c.offset);if(main)main.style.left=sidebarWidth+'px';
  sidebar?.classList.toggle('sidebar-collapsed',collapsed);main&&(main.style.flex='1 1 auto');
  if(name==='feedback'||name==='plan'){const header=node(name==='feedback'?'16:73478':'25:81382'),newVersion=node(name==='feedback'?'16:73479':'25:81383'),toggle=node(name==='feedback'?'16:73480':'25:81384');if(header)setSize(header,collapsed?32:196,32);if(newVersion)newVersion.style.display=collapsed?'none':'flex';if(toggle){toggle.style.left=collapsed?'0px':'164px';toggle.style.position='absolute';}}
  if(c.video){const panel=node(c.panel);fitWorkspace(main,node(c.video),panel,c.vw,c.vh);if(name==='feedback')fitFeedbackContent(panel);if(name==='plan')fitPlanContent(panel);}
 }
 if(name==='home'){
  const page=node('17:74146'),mainWidth=width-sidebarWidth,hero=node('17:74944'),heroWidth=Math.min(868,Math.max(500,mainWidth-48));setSize(page,mainWidth,height-52);setSize(node('18:81375'),mainWidth,height-50);
  if(hero){setSize(hero,heroWidth,Math.max(566,height-172));hero.style.left='50%';hero.style.transform='translateX(-50%)';const intro=node('17:76212');if(intro)intro.style.left=Math.max(0,(heroWidth-633)/2)+'px';const projects=node('17:74955'),header=node('17:76172'),search=node('17:76177');setSize(projects,heroWidth,null);setSize(header,heroWidth,32);if(search)search.style.left=Math.max(148,heroWidth-287.286)+'px';const cards=['17:76477','17:76495','17:76579','17:76669','17:76651'].map(node).filter(Boolean),columns=heroWidth>=840?3:heroWidth>=560?2:1,gap=12,cardWidth=(heroWidth-gap*(columns-1))/columns;cards.forEach((card,index)=>{projects.append(card);Object.assign(card.style,{left:(index%columns)*(cardWidth+gap)+'px',top:(52+Math.floor(index/columns)*122)+'px',width:cardWidth+'px',height:'110px'});card.querySelectorAll(':scope > [data-node-id]').forEach(el=>el.style.width=parseFloat(el.style.height||0)>30?'calc(100% - 40px)':'16px');});}
 }
 if(name==='new-project'){const page=node('25:81992');setSize(page,width-sidebarWidth,height-52);}
 if(name==='candidates'){
  const candidateSidebarWidth=state.candidateSidebarCollapsed?56:220,content=node('14:72081'),candidateSidebar=node('14:73212');setSize(content,width,height-116);setSize(candidateSidebar,candidateSidebarWidth,height-116);setSize(node('14:72144'),width-candidateSidebarWidth,height-116);
  const main=node('14:72144');if(main)Object.assign(main.style,{left:candidateSidebarWidth+'px',overflow:'hidden'});
  const agentHeight=state.generating?140:95,rowTop=state.generating?172:127,footerTop=height-168,rowHeight=Math.max(280,footerTop-rowTop-16),workspaceWidth=width-candidateSidebarWidth-32;setSize(node('14:72183'),workspaceWidth,agentHeight);setSize(node('14:72234'),workspaceWidth,rowHeight);setSize(node('14:72384'),workspaceWidth,36);const row=node('14:72234');if(row)Object.assign(row.style,{top:rowTop+'px',overflow:'hidden'});const footer=node('14:72384');if(footer)Object.assign(footer.style,{top:footerTop+'px',overflow:'visible'});
  const agent=node('14:72183'),agentBg=node('14:72184'),agentContent=node('14:72203'),agentHeader=node('14:72204'),steps=node('14:72220'),agentCopy=node('14:72226');if(agent)agent.style.overflow='hidden';if(agentBg)Object.assign(agentBg.style,{inset:'0px',width:'100%',height:'100%'});if(agentContent)Object.assign(agentContent.style,{left:'16px',width:'calc(100% - 32px)'});if(agentHeader)agentHeader.style.width='100%';if(steps)Object.assign(steps.style,{left:'auto',right:'0px'});if(agentCopy)agentCopy.style.width='100%';
  const cardIds=['14:72235','14:72276','14:72317'],rowWidth=workspaceWidth,cardWidth=(rowWidth-32)/3;
  const headIds=['14:72236','14:72277','14:72318'],titleIds=['14:72237','14:72278','14:72319'],descriptionIds=['14:72239','14:72279','14:72320'],stageIds=['14:72240','14:72280','14:72321'],portraitIds=['14:72241','14:72281','14:72322'],playIds=['14:72242','14:72283','14:72323'],timelineIds=['14:72246','14:72287','14:72327'];
  cardIds.forEach((id,index)=>{const card=node(id);if(!card)return;Object.assign(card.style,{left:(index*(cardWidth+16))+'px',width:cardWidth+'px',height:rowHeight+'px',flex:'none',overflow:'hidden'});const head=node(headIds[index]),title=node(titleIds[index]),description=node(descriptionIds[index]),stage=node(stageIds[index]),portrait=node(portraitIds[index]),play=node(playIds[index]),timeline=node(timelineIds[index]);if(head)Object.assign(head.style,{left:'12px',width:'calc(100% - 24px)'});if(title)title.style.width='calc(100% - 74px)';if(description)Object.assign(description.style,{width:'100%',minWidth:'0'});if(stage)Object.assign(stage.style,{left:'12px',top:'84px',width:'calc(100% - 24px)',height:Math.max(170,rowHeight-96)+'px',minHeight:'0',overflow:'hidden'});if(portrait)Object.assign(portrait.style,{height:'100%',width:'auto',left:'50%',transform:'translateX(-50%)'});if(play)play.style.left='50%';if(timeline)Object.assign(timeline.style,{left:'50%',width:Math.max(180,Math.min(335,cardWidth-40))+'px'});});
  const footerActions=node('14:72387'),footerMessage=node('14:72385');if(footerActions)Object.assign(footerActions.style,{left:'auto',right:'0px'});if(footerMessage)footerMessage.style.display=rowWidth<930?'none':'flex';
 }
 if(name==='preview'){
  const content=node('14:72489'),outer=node('14:73201'),workspace=node('14:73244');setSize(content,width,height-52);setSize(outer,width-32,height-84);setSize(workspace,width-32,height-122);
  if(workspace){workspace.style.width='100%';fitWorkspace(workspace,node('14:72848'),node('14:73245'),851,778);}
 }
 root.querySelectorAll('[data-node-id$="68931"],[data-node-id="16:73796"],[data-node-id="14:71994"],[data-node-id="14:72402"],[data-node-id="25:81883"],[data-node-id="11:68872"]').forEach(el=>el.style.width='100%');
 root.querySelectorAll('[data-node-id="11:67504"],[data-node-id="25:81450"],[data-node-id="25:81487"]').forEach(el=>el.style.width='100%');
}
function scale(){adaptLayout(root.dataset.screen||'home');}
addEventListener('resize',scale);addEventListener('hashchange',()=>show(location.hash.slice(1)));show(location.hash.slice(1)||'home');

async function geometry(name){
 const ids={home:'16-73795','new-project':'25-81862',feedback:'11-65277',plan:'11-68513',candidates:'14-71993',preview:'14-72401'};
 const list=await(await fetch('source/geo-'+ids[name]+'.json')).json();
 const map=new Map(list.map(r=>[r[0],r]));const rotations=new Map(await(await fetch('source/rotations.json')).json());
 for(const [id,parent,x,y,w,h,fonts] of list){
  const el=root.querySelector('[data-node-id="'+id+'"]');if(!el)continue;
  el.style.width=w+'px';el.style.height=h+'px';el.style.flex='none';el.style.minWidth='0';el.style.minHeight='0';
  const siblings=[...el.parentElement.children];const positioned=siblings.every(s=>map.get(s.dataset.nodeId)?.[1]===parent&&!/translate|rotate|skew/.test(s.className)&&!s.style.transform);
  if(el.parentElement.dataset.nodeId===parent&&positioned){const ps=getComputedStyle(el.parentElement);Object.assign(el.style,{position:'absolute',left:(x-(Math.abs(rotations.get(id)||0)>179?w:0)-parseFloat(ps.borderLeftWidth||0))+'px',top:(y-(Math.abs(rotations.get(id)||0)>179?h:0)-parseFloat(ps.borderTopWidth||0))+'px',right:'auto',bottom:'auto',margin:0});}
  if(fonts?.length===1){const f=fonts[0];el.style.fontFamily='"'+f.family+'"';el.style.fontWeight=/Semi Bold/.test(f.style)?600:/Bold/.test(f.style)?700:/Medium/.test(f.style)?500:400;}
 }
}

const stateKey='tiktok-figma-exact-state';let state;try{state=JSON.parse(localStorage.getItem(stateKey))}catch{}state={selected:null,previewCandidate:0,feedback:[],choices:[null,null],customDirections:[[],[]],skipped:[false,false],shotOpen:[true,true,false,false],versionOpen:[true,false,false],versions:[{base:'Source Video',generated:false}],currentVersion:0,rounds:[],plannedChanges:['Trim the pause before the first line so the creator starts speaking sooner.','Replace “Shop the cushion now” with “I’ve linked the cushion if you’re curious.” Keep the shot of the compact going into the bag.'],projectName:'Summer Sunscreen Cushion',base:'Source Video',sidebarCollapsed:false,candidateSidebarCollapsed:true,generating:false,generationStartedAt:0,...(state||{})};if(state.schemaVersion!==4){state.selected=null;state.previewCandidate=0;state.feedback=[];state.choices=[null,null];state.customDirections=[[],[]];state.skipped=[false,false];state.shotOpen=[true,true,false,false];state.versionOpen=[true,false,false];state.versions=[{base:'Source Video',generated:false}];state.currentVersion=0;state.plannedChanges=['Trim the pause before the first line so the creator starts speaking sooner.','Replace “Shop the cushion now” with “I’ve linked the cushion if you’re curious.” Keep the shot of the compact going into the bag.'];state.generating=false;state.schemaVersion=4;}let selectedFile=null,sourceUrl=null,playing=null,generationTimer=null,clock=6;
const persist=()=>localStorage.setItem(stateKey,JSON.stringify(state));
const node=id=>root.querySelector('[data-node-id="'+id+'"]');
function tell(message){const n=document.getElementById('notice');n.textContent=message;n.style.display='block';setTimeout(()=>n.style.display='none',4000);}
function nav(name){clearInterval(playing);playing=null;clearTimeout(generationTimer);generationTimer=null;location.hash=name;if(root.dataset.screen===name)show(name);}
function leaf(text){return [...root.querySelectorAll('p,span,div')].find(el=>el.textContent.trim()===text&&(!el.children.length||el.tagName==='P'));}
function click(el,fn,label){if(!el)return;el.classList.add('interactive');el.tabIndex=0;el.setAttribute('role','button');if(label)el.setAttribute('aria-label',label);el.onclick=e=>{e.stopPropagation();fn(e);};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fn(e);}};}
function button(text,fn){let el=leaf(text);if(!el)return;let outer=el;for(let p=el.parentElement;p&&p!==root;p=p.parentElement){if(/^Button/.test(p.dataset.name||'')){outer=p;break;}}click(outer,fn,text);return outer;}
function modal(title,body,onSave){const wrap=document.createElement('div');wrap.className='native-overlay';const panel=document.createElement('section');panel.className='native-panel';panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');const heading=document.createElement('h2');heading.textContent=title;panel.append(heading);if(typeof body==='string'){const p=document.createElement('p');p.textContent=body;panel.append(p);}else panel.append(body);const close=document.createElement('button');close.textContent='Cancel';close.onclick=()=>wrap.remove();panel.append(close);if(onSave){const save=document.createElement('button');save.textContent='Save';save.className='primary';save.onclick=()=>{if(onSave()!==false)wrap.remove();};panel.append(save);}else close.textContent='Close';wrap.append(panel);document.body.append(wrap);(panel.querySelector('textarea,input')||close).focus();wrap.onkeydown=e=>{if(e.key==='Escape')wrap.remove();};return wrap;}
function renameProject(){
 const field=document.createElement('div');field.className='rename-field';field.innerHTML='<label for="rename-project-input">Project name</label>';
 const input=document.createElement('input');input.id='rename-project-input';input.value=state.projectName||'Summer Sunscreen Cushion';input.maxLength=80;field.append(input);
 const wrap=modal('Rename project',field,()=>{const value=input.value.trim();if(!value){input.setAttribute('aria-invalid','true');return false;}state.projectName=value;persist();show(root.dataset.screen);tell('Project name updated.');});
 wrap.querySelector('.native-panel').classList.add('rename-project-panel');
}
function installSidebarToggle(name){
 const ids={home:'17:75358','new-project':'25:81939',feedback:'16:73477',plan:'25:81381'},sidebar=node(ids[name]);if(!sidebar)return;
 sidebar.classList.add('app-sidebar');
 const toggle=()=>{state.sidebarCollapsed=!state.sidebarCollapsed;persist();adaptLayout(name);installSidebarToggle(name);};
 if(name==='home'||name==='new-project'){
  const old=leaf('Collapse Sidebar');if(old){let control=old;while(control.parentElement&&control.parentElement!==sidebar&&parseFloat(control.style.height||0)<32)control=control.parentElement;click(control,toggle,state.sidebarCollapsed?'Expand sidebar':'Collapse sidebar');}
 }else{
  const toggleIds={feedback:'16:73480',plan:'25:81384'},control=node(toggleIds[name]);click(control,toggle,state.sidebarCollapsed?'Expand sidebar':'Collapse sidebar');
 }
}
function setPlaybackTime(seconds,label){clock=seconds;const stage=root.querySelector('[data-name^="Main Video Stage"]'),video=stage?.querySelector('video');if(video)video.currentTime=seconds;root.querySelectorAll('p').forEach(p=>{if(/^00:\d{2}$/.test(p.textContent))p.textContent='00:'+String(seconds).padStart(2,'0');});tell('Jumped to '+label+' · 00:'+String(seconds).padStart(2,'0'));}
function wireVersionAccordions(name){
 const cfg=name==='feedback'?{list:'16:73481',cards:['16:73482','16:73516','16:73527'],details:'16:73493'}:name==='plan'?{list:'25:81385',cards:['25:81386','25:81420','25:81431'],details:'25:81397'}:null;if(!cfg)return;
 const list=node(cfg.list),cards=cfg.cards.map(node);if(!list||cards.some(c=>!c))return;Object.assign(list.style,{display:'flex',flexDirection:'column',gap:'12px',overflowY:'auto'});
 cards.forEach((card,index)=>{const version=state.versions[index];card.style.display=version?'block':'none';if(!version)return;Object.assign(card.style,{position:'relative',left:'auto',top:'auto',width:'196px',flex:'none',overflow:'hidden'});if(index===0){const detail=node(cfg.details);if(detail)[...detail.querySelectorAll('p')].filter(p=>['A Tighter Edit','Product in Use','An Everyday Story'].includes(p.textContent.trim())).forEach(p=>{let item=p;while(item.parentElement!==detail&&item.parentElement)item=item.parentElement;item.style.display=version.generated?'flex':'none';});}else{let options=card.querySelector('.version-candidates');if(!options){options=document.createElement('div');options.className='version-candidates';card.append(options);}options.replaceChildren();const base=document.createElement('button');base.type='button';base.innerHTML='<span>'+version.base+'</span><small>Base</small>';options.append(base);if(version.generated)['A Tighter Edit','Product in Use','An Everyday Story'].forEach((title,i)=>{const item=document.createElement('button');item.type='button';item.innerHTML='<span>'+title+'</span><small>'+String(index+1)+'-'+String.fromCharCode(65+i)+'</small>';item.onclick=e=>{e.stopPropagation();state.previewCandidate=i;persist();nav('preview');};options.append(item);});}
  const header=[...card.querySelectorAll('p')].find(p=>p.textContent.trim()==='Version '+(index+1));if(header){let target=header.parentElement;while(target.parentElement&&target.parentElement!==card&&parseFloat(target.style.height||0)<38)target=target.parentElement;click(target,()=>{state.versionOpen[index]=!state.versionOpen[index];persist();render();},'Toggle Version '+(index+1));}
 });
 function render(){cards.forEach((card,index)=>{const version=state.versions[index];if(!version)return;const open=!!state.versionOpen[index],height=open?(version.generated?204:96):54;card.style.height=height+'px';card.setAttribute('aria-expanded',String(open));const detail=index===0?node(cfg.details):card.querySelector('.version-candidates');if(detail)detail.style.display=open?'flex':'none';const chevron=[...card.querySelectorAll('img')].find(img=>img.src.includes('svg'));if(chevron)chevron.closest('[class*="rotate"]')?.style.setProperty('rotate',open?'180deg':'0deg');});}
 render();
}
function wireCandidateSidebar(){
 const sidebar=node('14:73212'),toggle=node('14:73213'),tabs=node('14:73214');if(!sidebar||!toggle)return;click(toggle,()=>{state.candidateSidebarCollapsed=!state.candidateSidebarCollapsed;persist();adaptLayout('candidates');wireCandidateSidebar();},state.candidateSidebarCollapsed?'Expand sidebar':'Collapse sidebar');if(tabs)tabs.style.display=state.candidateSidebarCollapsed?'flex':'none';['14:73215','14:73219','14:73223'].forEach((id,index)=>{const tab=node(id);if(tab)tab.style.display=index<state.versions.length?'flex':'none';});let expanded=sidebar.querySelector('.candidate-expanded-sidebar');if(!expanded){expanded=document.createElement('div');expanded.className='candidate-expanded-sidebar';sidebar.append(expanded);}expanded.style.display=state.candidateSidebarCollapsed?'none':'flex';expanded.replaceChildren();state.versions.forEach((version,index)=>{const item=document.createElement('button');item.type='button';item.className=index===state.currentVersion?'active':'';item.innerHTML='<strong>Version '+(index+1)+'</strong><span>'+version.base+'</span>'+(version.generated?'<small>3 candidates</small>':'<small>Base video</small>');item.onclick=()=>{state.currentVersion=index;state.selected=null;persist();nav(version.generated?'candidates':'feedback');};expanded.append(item);});
}
function wireFeedbackAccordions(){
 const sc=node('25:82580')?.querySelector('.cards-scroll'),cards=['25:82631','25:82646','25:82666','25:82677'].map(node);if(!sc||cards.some(c=>!c))return;sc.classList.add('flow-scroll');
 const dynamic=[null,null,{description:'The creator applies the cushion across the cheeks and nose, showing the texture and finish.',prompt:'How does the application feel?',options:['The hand movement feels stiff','The demonstration feels repetitive']},{description:'The creator shows the finished look and closes with a shopping invitation.',prompt:'How does the ending feel?',options:['The closing feels too promotional','The final shot ends too quickly']}];
 cards.forEach((card,index)=>{Object.assign(card.style,{position:'relative',left:'auto',top:'auto',flex:'none',overflow:'hidden'});if(index>1&&!card.querySelector('.dynamic-shot-body')){const body=document.createElement('div');body.className='dynamic-shot-body';body.innerHTML='<p>'+dynamic[index].description+'</p><div class="dynamic-question">🤔 '+dynamic[index].prompt+'</div><div class="dynamic-options"></div><button type="button" class="dynamic-add">＋ Add my own feelings</button>';dynamic[index].options.forEach(text=>{const option=document.createElement('button');option.type='button';option.textContent=text;option.onclick=()=>{const active=state.feedback.includes(text);state.feedback=active?state.feedback.filter(t=>t!==text):[...state.feedback,text];persist();option.classList.toggle('chosen',!active);updateFeedbackCount();};body.querySelector('.dynamic-options').append(option);});card.append(body);}
  const header=card.firstElementChild;click(header,()=>{state.shotOpen[index]=!state.shotOpen[index];persist();render();},'Toggle '+(['Whole Video','Shot 1','Shot 2','Shot 4'][index]));
 });
 function render(){cards.forEach((card,index)=>{const open=!!state.shotOpen[index],openHeight=index===0?223:index===1?261:190;card.style.height=(open?openHeight:54)+'px';card.setAttribute('aria-expanded',String(open));[...card.children].slice(1).forEach(el=>el.style.display=open?'block':'none');const chevron=card.firstElementChild?.querySelector('[class*="rotate"]');if(chevron)chevron.style.rotate=open?'180deg':'0deg';});}
 render();
}
function updateFeedbackCount(){root.querySelectorAll('p').forEach(p=>{if(/^\d+ thoughts added$/.test(p.textContent))p.textContent=state.feedback.length+' thoughts added';});}
function showGeneratingState(){
 const duration=12000,elapsed=Date.now()-state.generationStartedAt;if(elapsed>=duration){state.generating=false;state.versions[state.currentVersion].generated=true;persist();show('candidates');return;}
 const thoughts=['Reviewing the confirmed change plan','Mapping each change to the relevant shots','Building three distinct editing directions','Rendering pacing, action, and story variations','Checking each candidate against the original feedback'];
 const agent=node('14:72183'),agentIcon=node('14:72206')?.cloneNode(true);if(agent){agent.classList.add('generation-agent');agent.innerHTML='<div class="agent-thinking"><div class="agent-thinking-title"><span class="thinking-orb"></span><strong>Video Agent is working</strong><span class="thinking-dots"><i></i><i></i><i></i></span></div><p class="agent-thinking-current"></p><div class="agent-thinking-log"></div></div>';if(agentIcon)agent.querySelector('.thinking-orb').append(agentIcon);}
 ['14:72235','14:72276','14:72317'].forEach((id,index)=>{const card=node(id);if(!card)return;card.classList.add('generation-placeholder');card.setAttribute('aria-busy','true');card.innerHTML='<div class="generation-glow glow-'+index+'"></div><div class="generation-skeleton"><span></span><span></span><span></span><div></div></div><p>Generating candidate '+String.fromCharCode(65+index)+'…</p>';});
 const footer=node('14:72384');if(footer)footer.style.visibility='hidden';
 const tick=()=>{if(root.dataset.screen!=='candidates'||!state.generating)return;const passed=Date.now()-state.generationStartedAt,index=Math.min(thoughts.length-1,Math.floor(passed/2200)),current=root.querySelector('.agent-thinking-current'),log=root.querySelector('.agent-thinking-log');if(current)current.textContent=thoughts[index]+'…';if(log)log.textContent=index?thoughts.slice(0,index).join('  ·  '):'Preparing the workspace';if(passed>=duration){state.generating=false;state.versions[state.currentVersion].generated=true;persist();show('candidates');return;}generationTimer=setTimeout(tick,700);};tick();
}
function startGeneration(){if(!state.choices.every((choice,index)=>choice!=null||state.skipped[index]))return;state.rounds.push({version:state.currentVersion,base:state.base,feedback:[...state.feedback],choices:[...state.choices],created:Date.now()});state.selected=null;state.generating=true;state.generationStartedAt=Date.now();persist();nav('candidates');}
function inputAt(text,placeholder,value,change){const el=leaf(text);if(!el)return;const inp=document.createElement('input');inp.className='inline-input';inp.placeholder=placeholder;inp.value=value||'';inp.setAttribute('aria-label',placeholder);inp.oninput=()=>change(inp.value);el.replaceChildren(inp);return inp;}
function scrollCards(screen){const config=screen==='feedback'?['25:82580',110,690,['25:82631','25:82646','25:82666','25:82677']]:screen==='plan'?['11:68704',91,690,['11:68755','13:69198']]:screen==='preview'?['14:73245',98,716,['14:73296','14:73311','14:73331','14:73406','16:73462']]:null;if(!config)return;const [id,start,end,ids]=config,parent=node(id),sc=document.createElement('div');sc.className='cards-scroll';Object.assign(sc.style,{position:'absolute',left:'0',top:start+'px',width:'100%',height:(end-start)+'px',overflowY:'auto',scrollbarWidth:'none'});parent.append(sc);ids.forEach(id=>{const el=node(id);if(!el)return;el.style.top=(parseFloat(el.style.top)-start)+'px';sc.append(el);});if(screen==='plan'){sc.classList.add('flow-scroll');sc.querySelectorAll(':scope > [data-node-id]').forEach(el=>Object.assign(el.style,{position:'relative',left:'auto',top:'auto',width:'100%',flex:'none'}));}}
function wire(name){
 const backgrounds={feedback:'25:82581',plan:'11:68705',candidates:'14:72184'};if(backgrounds[name]){const bg=node(backgrounds[name]);bg.replaceChildren();bg.style.background='url(assets/backdrop-'+name+'.png) left top / 100% auto no-repeat';bg.style.border=0;}
 scrollCards(name);
 installSidebarToggle(name);
 if(name==='candidates')wireCandidateSidebar();
 wireVersionAccordions(name);
 button('TikTok Shop Video Studio',()=>nav('home'));
 if(name==='home'||name==='new-project'){
  button('Start Refining',()=>tell('Creating a new project is not available in this prototype yet. Open “Summer Sunscreen Cushion” to explore the full flow.'));
  const titles=['Summer Sunscreen Cushion','Everyday Lip Tint','Weekend Sneaker Edit','Morning Coffee Routine','Travel Skincare Essentials'];
  titles.forEach((text,index)=>{const el=leaf(text);if(!el)return;if(index===0&&state.projectName&&state.projectName!==text)el.textContent=state.projectName;let card=el;while(card.parentElement&&parseFloat(card.style.height||0)<90)card=card.parentElement;click(card,()=>{if(index===0){state.projectName=el.textContent.trim();persist();nav('feedback');}else tell('This project is not available in this prototype yet. Open “'+(state.projectName||titles[0])+'” to explore the full flow.');},'Open '+text);});
  inputAt('Search project name','Search project name','',value=>{titles.forEach(t=>{const el=leaf(t);if(!el)return;let card=el;while(card.parentElement&&parseFloat(card.style.height||0)<90)card=card.parentElement;card.style.visibility=t.toLowerCase().includes(value.toLowerCase())?'visible':'hidden';});});
  button('Video Refining',()=>nav('home'));
  root.querySelectorAll('[data-name="semi-icons-Star_stroked"]').forEach(el=>click(el,()=>{el.style.opacity=el.style.opacity==='0.4'?'1':'0.4';},'Toggle favorite'));
 }
 if(name==='new-project'){
  inputAt('Please enter','Please enter',state.newName||'',v=>{state.newName=v;persist();});
  button('Cancel',()=>nav('home'));root.querySelectorAll('[data-name="semi-icons-close"]').forEach(el=>click(el,()=>nav('home'),'Close'));
  const target=leaf('Click to Upload File or Drag File to here');const area=target?.closest('[data-name="Content"]')||target?.parentElement?.parentElement;
  const file=document.createElement('input');file.type='file';file.accept='.mp4,video/mp4';file.hidden=true;file.id='video-upload';root.append(file);
  const take=f=>{if(!f)return;if(!/\.mp4$/i.test(f.name)){tell('Only .mp4 files are supported.');return;}selectedFile=f;if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=URL.createObjectURL(f);if(target)target.textContent=f.name;};file.onchange=()=>take(file.files[0]);click(area,()=>file.click(),'Upload video');if(area){area.ondragover=e=>e.preventDefault();area.ondrop=e=>{e.preventDefault();take(e.dataTransfer.files[0]);};}
  button('Create',()=>{if(!state.newName?.trim()){tell('Please enter a project name.');return;}if(!selectedFile){tell('Please upload an MP4 video.');return;}state.projectName=state.newName.trim();persist();nav('feedback');});
 }
 if(['feedback','plan'].includes(name)){
  const projectTitle=leaf('Summer Sunscreen Cushion');if(projectTitle){projectTitle.textContent=state.projectName||'Summer Sunscreen Cushion';click(projectTitle,renameProject,'Rename project');const edit=projectTitle.nextElementSibling;click(edit,renameProject,'Rename project');}
  ['A Tighter Edit','Product in Use','An Everyday Story'].forEach((text,i)=>button(text,()=>{state.selected=i;persist();nav('preview');}));
  button('New Version',()=>{state.base='Source Video';state.feedback=[];persist();nav('feedback');});
  root.querySelectorAll('[data-name="Button_Borderless"]').forEach(el=>{if(el.querySelector('img')?.src.includes('svg')&&parseFloat(el.style.width)===32&&el.parentElement.dataset.nodeId?.includes('67505'))click(el,()=>nav('home'),'Back to projects');});
 }
 if(name==='feedback'){
  wireFeedbackAccordions();
  button('Let’s Plan the Changes',()=>{persist();nav('plan');});
  button('View Details',()=>{const box=document.createElement('div');const list=document.createElement('ul');const items=state.feedback.length?state.feedback:['Feels too much like an ad','Pacing feels slow','Takes too long to get to the point','More natural product placement','More natural hand movements','A softer closing'];items.forEach(t=>{const li=document.createElement('li');li.textContent=t;list.append(li);});box.append(list);modal('Your thoughts',box);});
  root.querySelectorAll('[data-name="Tag Radio"]').forEach(el=>{const text=el.textContent.trim(),selected=state.feedback.includes(text);el.classList.toggle('chosen',selected);el.classList.toggle('unchosen',!selected);click(el,()=>{const has=state.feedback.includes(text);state.feedback=has?state.feedback.filter(t=>t!==text):[...state.feedback,text];el.classList.toggle('chosen',!has);el.classList.toggle('unchosen',has);updateFeedbackCount();persist();},text);});updateFeedbackCount();
  [...root.querySelectorAll('p')].filter(p=>p.textContent==='Add my own feelings').forEach(el=>click(el.parentElement,()=>{const input=document.createElement('textarea');input.placeholder='Tell me what you’d like to change';input.value=state.note||'';input.oninput=()=>{state.note=input.value;persist();};modal('Add my own feelings',input,()=>{if(!input.value.trim())return false;state.feedback.push(input.value.trim());state.note='';persist();tell('Your thought has been added.');});},'Add my own feelings'));
 }
 if(name==='plan'){
  button('Back to Feedback',()=>nav('feedback'));
  let generateButton;const updateGenerate=()=>{const ready=state.choices.every((choice,index)=>choice!=null||state.skipped[index]);if(generateButton){generateButton.classList.toggle('action-disabled',!ready);generateButton.setAttribute('aria-disabled',String(!ready));generateButton.style.pointerEvents=ready?'auto':'none';}}
  const labels=['Show the compact being picked up and opened','Shorten the standalone product close-up','Make the tapping motion more relaxed','Smooth out the movement around the nose'];
  labels.forEach((text,i)=>{const el=leaf(text);if(!el)return;let card=el;while(card.parentElement&&parseFloat(card.style.height||0)<40)card=card.parentElement;const group=Math.floor(i/2),choice=i%2;card.dataset.questionGroup=group;card.classList.toggle('chosen',state.choices[group]===choice);card.classList.toggle('unchosen',state.choices[group]!==choice);click(card,()=>{if(state.skipped[group])return;state.choices[group]=choice;persist();show('plan');},text);});
  const groups=[node('11:68762'),node('13:69042')],containers=[node('11:68765'),node('13:69046')];containers.forEach((container,group)=>{const actions=container?.children[2];(state.customDirections[group]||[]).forEach((value,index)=>{const option=document.createElement('button');option.type='button';option.className='custom-direction-option '+(state.choices[group]==='custom-'+index?'chosen':'unchosen');option.dataset.questionGroup=group;option.style.top=(110+index*55)+'px';option.innerHTML='<b>'+String.fromCharCode(67+index)+'.</b><span><strong>'+value+'</strong><small>Your direction</small></span>';option.onclick=()=>{state.choices[group]='custom-'+index;persist();show('plan');};container.insertBefore(option,actions);});});
  const adds=[...root.querySelectorAll('p')].filter(el=>el.textContent==='Add my own direction');adds.forEach((el,i)=>click(el.parentElement,()=>{if(state.skipped[i])return;const input=document.createElement('textarea');input.placeholder='Describe your direction';modal('Add my own direction',input,()=>{const value=input.value.trim();if(!value)return false;state.customDirections[i].push(value);state.choices[i]='custom-'+(state.customDirections[i].length-1);persist();show('plan');});},'Add my own direction'));
  const skips=[...root.querySelectorAll('p')].filter(el=>el.textContent==='Skip question');function questionHeight(i){return state.skipped[i]?(i===0?43:76):(i===0?153:169.5)+(state.customDirections[i]?.length||0)*55;}function renderSkip(i){const skipped=!!state.skipped[i],customCount=state.customDirections[i]?.length||0;root.querySelectorAll('[data-question-group="'+i+'"]').forEach(card=>card.style.display=skipped?'none':'flex');const add=adds[i]?.parentElement;if(add){add.classList.toggle('direction-disabled',skipped);add.setAttribute('aria-disabled',String(skipped));}if(skips[i])skips[i].textContent=skipped?'Cancel skip':'Skip question';const content=groups[i]?.children[1],actions=content?.children[content.children.length-1];if(groups[i])groups[i].style.height=questionHeight(i)+'px';if(actions)actions.style.top=skipped?'0px':(110+customCount*55)+'px';const h1=questionHeight(0),h2=questionHeight(1);if(groups[1])groups[1].style.top=(54+h1+16)+'px';const questions=node('11:68755');if(questions)questions.style.height=(54+h1+16+h2+16)+'px';updateGenerate();}skips.forEach((el,i)=>click(el.parentElement,()=>{state.skipped[i]=!state.skipped[i];if(state.skipped[i])state.choices[i]=null;persist();show('plan');},'Skip or restore question '+(i+1)));skips.forEach((_,i)=>renderSkip(i));
  const changeItems=[node('13:69272'),node('13:69281')],changesWrap=node('13:69287');if(changesWrap)Object.assign(changesWrap.style,{display:'flex',flexDirection:'column',gap:'8px'});changeItems.forEach((item,index)=>{if(!item)return;const value=['Trim the pause before the first line so the creator starts speaking sooner.','Replace “Shop the cushion now” with “I’ve linked the cushion if you’re curious.” Keep the shot of the compact going into the bag.'][index];item.style.display=state.plannedChanges.includes(value)?'flex':'none';Object.assign(item.style,{position:'relative',left:'auto',top:'auto',width:'100%',flex:'none'});click(item,e=>{document.querySelector('.plan-item-menu')?.remove();const menu=document.createElement('div');menu.className='plan-item-menu';menu.innerHTML='<button type="button">Delete</button>';const rect=item.getBoundingClientRect();Object.assign(menu.style,{left:Math.min(rect.right-96,innerWidth-108)+'px',top:Math.min(rect.bottom+6,innerHeight-52)+'px'});menu.querySelector('button').onclick=()=>{state.plannedChanges=state.plannedChanges.filter(change=>change!==value);persist();menu.remove();show('plan');};document.body.append(menu);setTimeout(()=>addEventListener('click',event=>{if(!menu.contains(event.target))menu.remove();},{once:true}),0);},'Change options');});root.querySelectorAll('p').forEach(p=>{if(/Planned Changes$/.test(p.textContent.trim()))p.textContent='🎯 '+state.plannedChanges.length+' Planned Changes';});
  [...root.querySelectorAll('p')].filter(p=>/^Shot[1-4]$/.test(p.textContent.trim())).forEach(p=>{const shot=Number(p.textContent.trim().slice(4)),times={1:0,2:14,3:36,4:58};click(p.parentElement,()=>setPlaybackTime(times[shot],'Shot '+shot),'Jump to Shot '+shot);});
  generateButton=button('Generate New Videos',startGeneration);updateGenerate();
 }
 if(name==='candidates'){
  const projectTitle=leaf('Summer Sunscreen Cushion');if(projectTitle){projectTitle.textContent=state.projectName||'Summer Sunscreen Cushion';click(projectTitle,renameProject,'Rename project');click(projectTitle.nextElementSibling,renameProject,'Rename project');}
  const cardIds=['14:72235','14:72276','14:72317'];
  let refineButton,exportButton;const renderCandidateSelection=()=>{cardIds.forEach((id,i)=>node(id)?.classList.toggle('candidate-selected',state.selected===i));const enabled=state.selected!=null;[refineButton,exportButton].forEach(control=>{if(!control)return;control.classList.toggle('action-disabled',!enabled);control.setAttribute('aria-disabled',String(!enabled));control.style.pointerEvents=enabled?'auto':'none';});};
  cardIds.forEach((id,i)=>{const card=node(id),head=node(['14:72236','14:72277','14:72318'][i]);if(!card)return;click(card,()=>{if(state.generating)return;state.selected=i;persist();renderCandidateSelection();},'Select candidate '+String.fromCharCode(65+i));if(head&&!head.querySelector('.candidate-detail')){const detail=document.createElement('button');detail.type='button';detail.className='candidate-detail';detail.setAttribute('aria-label','View Detail for candidate '+String.fromCharCode(65+i));detail.innerHTML='<span>Detail</span><img src="assets/detail-arrow.svg" alt="">';detail.onclick=e=>{e.stopPropagation();state.previewCandidate=i;persist();nav('preview');};head.append(detail);}});
  [...root.querySelectorAll('[data-name^="Central Floating Play"]')].filter(el=>!el.dataset.name.endsWith(':shadow')).forEach((el,i)=>click(el,()=>{state.previewCandidate=i;persist();nav('preview');},'Preview candidate '+String.fromCharCode(65+i)));
  refineButton=button('Refine Candidate',refine);button('Back to Feedback',()=>nav('feedback'));exportButton=button('Export Video',()=>modal('Export Video','This prototype contains the Figma preview images. A playable candidate video is needed to export the actual result.'));['V1','V2','V3'].forEach((t,index)=>button(t,()=>{if(index>=state.versions.length)return;state.currentVersion=index;state.selected=null;persist();nav(state.versions[index].generated?'candidates':'feedback');}));renderCandidateSelection();
  if(state.generating)showGeneratingState();
 }
 if(name==='preview'){
  button('Back',()=>nav('candidates'));button('Refine in a new version',refine);
  click(node('14:73238'),()=>{state.previewCandidate=(state.previewCandidate+2)%3;persist();show('preview');},'Previous candidate');click(node('14:73240'),()=>{state.previewCandidate=(state.previewCandidate+1)%3;persist();show('preview');},'Next candidate');
  {const candidate=state.previewCandidate??state.selected??0,names=['A Tighter Edit','Product in Use','An Everyday Story'];const t=node('14:73393');if(t)t.textContent='Candidate '+String(state.currentVersion+1)+'-'+String.fromCharCode(65+candidate)+': '+names[candidate];const count=leaf('1/3');if(count)count.textContent=(candidate+1)+'/3';fetch('screens/candidates.html').then(r=>r.text()).then(html=>{if(root.dataset.screen!=='preview')return;const doc=new DOMParser().parseFromString(html,'text/html');const cards=['14:72235','14:72276','14:72317'];const image=doc.querySelector('[data-node-id="'+cards[candidate]+'"] img[src$=".png"]');const current=node('14:72854')?.querySelector('img');if(image&&current){current.src=image.src;current.style.height='100%';current.style.top='0';current.style.objectFit='cover';}});}
 }
 if(['feedback','plan','preview'].includes(name)){
  root.querySelectorAll('[data-name^="Central Floating Play"]').forEach(el=>{if(el.dataset.name.endsWith(':shadow'))return;click(el,()=>togglePlayback(el),'Play or pause video');});
  root.querySelectorAll('[data-name="Button"]').forEach(el=>{if(el.querySelector('img')&&parseFloat(el.style.width)===16)click(el,()=>togglePlayback(el),'Video playback control');});
 }
 if(name!=='candidates')button('Export Video',()=>modal('Export Video','This prototype contains the Figma preview images. A playable candidate video is needed to export the actual result.'));
}
function refine(){const candidate=state.selected??state.previewCandidate;if(candidate==null)return;const base='Candidate '+String(state.currentVersion+1)+'-'+String.fromCharCode(65+candidate);if(state.versions.length<3){state.versions.push({base,generated:false});state.currentVersion=state.versions.length-1;state.versionOpen[state.currentVersion]=true;}else{state.currentVersion=state.versions.length-1;state.versions[state.currentVersion]={base,generated:false};}state.base=base;state.selected=null;state.previewCandidate=candidate;state.feedback=[];state.choices=[null,null];state.customDirections=[[],[]];state.skipped=[false,false];persist();nav('feedback');}
function togglePlayback(el){if(playing){clearInterval(playing);playing=null;tell('Paused');return;}if(sourceUrl&&root.dataset.screen==='feedback'){const stage=root.querySelector('[data-name^="Main Video Stage"]');let video=stage.querySelector('video');if(!video){video=document.createElement('video');video.src=sourceUrl;video.controls=true;Object.assign(video.style,{position:'absolute',inset:'0',width:'100%',height:'100%',objectFit:'contain',zIndex:2});stage.append(video);}video.play();return;}tell('Storyboard playback · Figma contains preview images, not video files.');playing=setInterval(()=>{clock=(clock+1)%85;root.querySelectorAll('p').forEach(p=>{if(/^00:\d{2}$/.test(p.textContent))p.textContent='00:'+String(clock).padStart(2,'0');});},1000);}
